import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { createClientExchangeListing, findCities, getClientExchangeListing, getClientExchangeMeta, publishClientExchangeListing, updateClientExchangeListing } from '../../api/clientExchange'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import PublicLayout from '../../layouts/PublicLayout'
import WizardStepProgress from '../../components/WizardStepProgress'

const styles=['/static/client-exchange.css?v=1','/static/wizard-step-progress.css?v=4','/static/client-exchange-create.css?v=4']
const stepNames=['Основное','Размер бизнеса','Особенности','Причина','Передача','Проверка']
const empty={title:'',client_inn:'',client_legal_name:'',industry_id:null,industry_ids:[],employee_range_id:null,tax_system_id:null,revenue_range_id:null,accounting_state_id:null,transfer_reason_id:null,transfer_reason_ids:[],transfer_type_id:null,transfer_reason_comment:'',transfer_price:null,monthly_commission_percent:null,commission_months:null,current_monthly_fee:null,operations_per_month:null,banks_count:null,has_vat:false,foreign_trade:false,bargain_allowed:false,region:'',city:'',client_since:null,desired_transfer_date:null,comment:'',current_step:1,marketplace_ids:[],edo_provider_ids:[],accounting_program_ids:[]}
const money=v=>v==null?'—':`${new Intl.NumberFormat('ru-RU').format(v)} ₽`

function StepHead({number,icon,title,text}){return <header className="step-head"><i>{icon}</i><div><small>ШАГ {number}</small><h2>{title}</h2><p>{text}</p></div></header>}
function Field({label,name,data,setData,type='text',wide=false,...props}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span><input type={type} name={name} value={data[name]??''} onChange={e=>setData(x=>({...x,[name]:type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value}))} {...props}/></label>}
function Select({label,name,kind,data,setData,dict,wide=false}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span><select value={data[name]??''} onChange={e=>setData(x=>({...x,[name]:e.target.value?Number(e.target.value):null}))}><option value="">Выберите вариант</option>{(dict[kind]||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function Choices({kind,name,data,setData,dict,multiple=false,icons=false}){const selected=multiple?data[name]||[]:[data[name]];return <div className="choice-grid compact">{(dict[kind]||[]).map((item,index)=><label className={`choice-card ${icons?'with-icon':''}`} key={item.id}><input type={multiple?'checkbox':'radio'} name={name} checked={selected.includes(item.id)} onChange={e=>setData(old=>{if(!multiple)return {...old,[name]:item.id};const values=old[name]||[];return {...old,[name]:e.target.checked?[...values,item.id]:values.filter(id=>id!==item.id)}})}/><span>{icons&&<i>{item.icon||['▣','◇','✓'][index%3]}</i>}<b>{item.name}</b>{item.description&&<small>{item.description}</small>}</span></label>)}</div>}
function fromListing(x){const industries=(x.industries?.length?x.industries:x.industry?[x.industry]:[]).map(v=>v.id),reasons=(x.transfer_reasons?.length?x.transfer_reasons:x.transfer_reason?[x.transfer_reason]:[]).map(v=>v.id);return {...empty,title:x.title||'',client_inn:x.private?.client_inn||'',client_legal_name:x.private?.client_legal_name||'',industry_id:industries[0]||null,industry_ids:industries,employee_range_id:x.employees?.id||null,tax_system_id:x.tax_system?.id||null,revenue_range_id:x.revenue?.id||null,accounting_state_id:x.accounting_state?.id||null,transfer_reason_id:reasons[0]||null,transfer_reason_ids:reasons,transfer_type_id:x.transfer_type?.id||null,transfer_reason_comment:x.transfer_reason_comment||'',transfer_price:x.transfer_price,monthly_commission_percent:x.monthly_commission_percent,commission_months:x.commission_months,current_monthly_fee:x.current_monthly_fee,operations_per_month:x.operations_per_month,banks_count:x.banks_count,has_vat:!!x.has_vat,foreign_trade:!!x.foreign_trade,bargain_allowed:!!x.bargain_allowed,region:x.region||'',city:x.city||'',client_since:x.client_since,desired_transfer_date:x.desired_transfer_date,comment:x.comment||'',current_step:x.current_step||1,marketplace_ids:(x.marketplaces||[]).map(v=>v.id),edo_provider_ids:(x.edo_providers||[]).map(v=>v.id),accounting_program_ids:(x.accounting_programs||[]).map(v=>v.id)}}

export default function ClientExchangeCreatePage(){useDocumentPage({title:'Передать клиента — FinTalent'});usePageStyles(styles);const [params,setParams]=useSearchParams(),navigate=useNavigate(),[id,setId]=useState(Number(params.get('id'))||0),[dict,setDict]=useState({}),[data,setData]=useState(empty),[step,setStep]=useState(1),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[toast,setToast]=useState(''),[published,setPublished]=useState(false),[cities,setCities]=useState([])
  useEffect(()=>{const controller=new AbortController();(async()=>{try{const meta=await getClientExchangeMeta({signal:controller.signal});setDict(meta.dictionaries||{});if(id){const listing=await getClientExchangeListing(id,{signal:controller.signal});if(!listing.is_owner)throw Error('Редактирование доступно только владельцу');const value=fromListing(listing);setData(value);setStep(Math.min(6,Math.max(1,value.current_step||1)))}setLoading(false)}catch(e){if(e.name!=='AbortError'){setToast(e.message);setTimeout(()=>navigate('/client-exchange'),1400)}}})();return()=>controller.abort()},[])
  useEffect(()=>{if(!data.city.trim()){setCities([]);return}const controller=new AbortController(),timer=setTimeout(()=>findCities(data.city,{signal:controller.signal}).then(setCities).catch(()=>{}),180);return()=>{clearTimeout(timer);controller.abort()}},[data.city])
  const find=(kind,id)=>(dict[kind]||[]).find(x=>x.id===Number(id)),transfer=find('transfer_type',data.transfer_type_id)
  const payload=()=>({...data,current_step:step,industry_id:data.industry_ids[0]||null,transfer_reason_id:data.transfer_reason_ids[0]||null})
  async function save(silent=false){if(saving)return false;setSaving(true);try{const saved=id?await updateClientExchangeListing(id,payload()):await createClientExchangeListing(payload());const nextId=saved?.id||id;if(!id){setId(nextId);setParams({id:String(nextId)},{replace:true})}if(!silent)setToast('Черновик сохранён');return true}catch(e){setToast(e.message);return false}finally{setSaving(false)}}
  const valid=()=>{const fail=m=>{setToast(m);return false};if(step===1&&!(data.industry_ids.length&&data.tax_system_id&&data.city.trim()))return fail('Выберите направление, город и налоговый режим');if(step===2&&!(data.revenue_range_id&&data.employee_range_id))return fail('Выберите размер бизнеса и количество сотрудников');if(step===3&&!data.accounting_state_id)return fail('Выберите состояние учёта');if(step===4&&!data.transfer_reason_ids.length)return fail('Выберите причину передачи');if(step===5&&(!transfer||(transfer.code==='fixed'&&data.transfer_price==null)||(['monthly_commission','term_commission'].includes(transfer.code)&&data.monthly_commission_percent==null)||(transfer.code==='term_commission'&&!data.commission_months)))return fail('Заполните условия передачи');return true}
  async function next(){if(!valid())return;if(step<6){if(await save(true)){setStep(step+1);scrollTo({top:0,behavior:'smooth'})}}else if(await save(true)){try{await publishClientExchangeListing(id);setPublished(true)}catch(e){setToast(e.message)}}}
  const progress=<WizardStepProgress steps={stepNames} current={step-1} onStepChange={index=>setStep(index+1)} ariaLabel="Прогресс создания карточки клиента"/>
  let content;if(step===1)content=<><StepHead number="1" icon="◇" title="Кого вы передаёте?" text="Укажите город, налоговый режим и направления клиента. Приватные данные нужны только для проверки."/><div className="fields"><Field label="ИНН клиента" name="client_inn" data={data} setData={setData} wide maxLength="12"/><Field label="Название клиента" name="client_legal_name" data={data} setData={setData}/><label className="field city-picker"><span>Город *</span><input value={data.city} onChange={e=>setData(x=>({...x,city:e.target.value,region:''}))} placeholder="Начните вводить город"/>{cities.length>0&&<div className="city-suggestions open">{cities.map(x=><button type="button" key={`${x.name}-${x.region}`} onClick={()=>{setData(old=>({...old,city:x.name,region:x.region||x.name}));setCities([])}}><b>{x.name}</b><small>{x.region}</small></button>)}</div>}</label><Select label="Система налогообложения *" name="tax_system_id" kind="tax_system" data={data} setData={setData} dict={dict}/><label className="field"><span>НДС</span><select value={String(data.has_vat)} onChange={e=>setData(x=>({...x,has_vat:e.target.value==='true'}))}><option value="false">Нет</option><option value="true">Да</option></select></label><div className="field wide industry-field"><span>Направления *</span><Choices kind="industry" name="industry_ids" data={data} setData={setData} dict={dict} multiple/></div></div></>
  if(step===2)content=<><StepHead number="2" icon="₽" title="Размер бизнеса" text="Укажите оборот, команду, банки и операции."/><div className="fields business-size-fields"><section className="number-panel third"><i>🏦</i><Field label="Количество банков" name="banks_count" type="number" data={data} setData={setData}/></section><section className="number-panel third"><i>⇄</i><Field label="Операций в месяц" name="operations_per_month" type="number" data={data} setData={setData}/></section><section className="number-panel third fee-panel"><i>₽</i><Field label="Стоимость обслуживания, ₽ / мес." name="current_monthly_fee" type="number" data={data} setData={setData}/></section><section className="choice-section half"><header><b>Размер бизнеса *</b></header><Choices kind="revenue_range" name="revenue_range_id" data={data} setData={setData} dict={dict}/></section><section className="choice-section half"><header><b>Количество сотрудников *</b></header><Choices kind="employee_range" name="employee_range_id" data={data} setData={setData} dict={dict}/></section></div></>
  if(step===3)content=<><StepHead number="3" icon="▦" title="Особенности клиента" text="Выберите площадки, ЭДО, программы и состояние учёта."/><div className="fields feature-fields">{[['marketplace','marketplace_ids','Маркетплейсы'],['edo_provider','edo_provider_ids','Операторы ЭДО'],['accounting_program','accounting_program_ids','Бухгалтерские программы']].map(([kind,name,title])=><section className="choice-section half" key={kind}><header><b>{title}</b></header><Choices kind={kind} name={name} data={data} setData={setData} dict={dict} multiple icons/></section>)}<label className="field wide switch"><input type="checkbox" checked={data.foreign_trade} onChange={e=>setData(x=>({...x,foreign_trade:e.target.checked}))}/><i></i><span>Есть внешнеэкономическая деятельность</span></label><Select label="Состояние учёта *" name="accounting_state_id" kind="accounting_state" data={data} setData={setData} dict={dict} wide/></div></>
  if(step===4)content=<><StepHead number="4" icon="!" title="Почему вы передаёте клиента?" text="Причина будет показана покупателю."/><section className="choice-section wide"><Choices kind="transfer_reason" name="transfer_reason_ids" data={data} setData={setData} dict={dict} multiple/></section><label className="field wide reason-comment"><span>Дополнительный комментарий</span><textarea value={data.transfer_reason_comment} onChange={e=>setData(x=>({...x,transfer_reason_comment:e.target.value}))} maxLength="2000"/></label></>
  if(step===5)content=<><StepHead number="5" icon="₽" title="Условия передачи" text="Выберите модель передачи и укажите желаемые условия."/><section className="choice-section wide"><Choices kind="transfer_type" name="transfer_type_id" data={data} setData={setData} dict={dict} icons/></section><div className="transfer-fields">{transfer?.code==='fixed'&&<Field label="Цена передачи, ₽" name="transfer_price" type="number" data={data} setData={setData} wide/>}{['monthly_commission','term_commission'].includes(transfer?.code)&&<Field label="Комиссия, %" name="monthly_commission_percent" type="number" data={data} setData={setData}/>} {transfer?.code==='term_commission'&&<Field label="Срок комиссии, месяцев" name="commission_months" type="number" data={data} setData={setData}/>}<label className="switch"><input type="checkbox" checked={data.bargain_allowed} onChange={e=>setData(x=>({...x,bargain_allowed:e.target.checked}))}/><i></i><span>Возможен торг</span></label></div><div className="fields transfer-extra"><Field label="Желаемая дата передачи" name="desired_transfer_date" type="date" data={data} setData={setData}/><Field label="Клиент обслуживается с" name="client_since" type="date" data={data} setData={setData}/><label className="field wide"><span>Дополнительная информация</span><textarea value={data.comment} onChange={e=>setData(x=>({...x,comment:e.target.value}))}/></label></div></>
  if(step===6)content=<><StepHead number="6" icon="✓" title="Проверьте объявление" text="Так карточка будет выглядеть для пользователей каталога."/><article className="preview-card"><header><div><small>{data.city||'Город не указан'}</small><h3>{find('industry',data.industry_ids[0])?.name||'Клиент'}</h3></div><b>{find('tax_system',data.tax_system_id)?.name||'—'} · {data.has_vat?'НДС':'Без НДС'}</b></header><section className="reason-big"><h3>ПРИЧИНА ПЕРЕДАЧИ</h3><p><b>{data.transfer_reason_ids.map(x=>find('transfer_reason',x)?.name).filter(Boolean).join(', ')||'—'}</b><br/>{data.transfer_reason_comment}</p></section><div className="key-grid"><div><small>Выручка</small><b>{find('revenue_range',data.revenue_range_id)?.name||'—'}</b></div><div><small>Сотрудники</small><b>{find('employee_range',data.employee_range_id)?.name||'—'}</b></div><div><small>Абонплата</small><b>{money(data.current_monthly_fee)}</b></div><div><small>Операций</small><b>{data.operations_per_month??'—'}</b></div></div><footer><div><small>УСЛОВИЯ ПЕРЕДАЧИ</small><h3>{transfer?.code==='fixed'?money(data.transfer_price):transfer?.name||'—'}</h3></div></footer></article><div className="privacy-note">✓ ИНН, юридическое название и контакты клиента скрыты от публичного просмотра.</div></>
  if(loading)return <PublicLayout><main className="wizard-page"><div className="loading">Загрузка…</div></main></PublicLayout>;return <PublicLayout><main className="wizard-page"><header className="wizard-title"><a href="/client-exchange">← Вернуться в каталог</a><span>ПЕРЕДАЧА КЛИЕНТА</span><h1>Создайте карточку клиента</h1><p>ИНН, название и контакты клиента не будут доступны в публичном каталоге.</p></header>{published?<section className="wizard-card"><div className="success-screen"><div className="success-mark">✓</div><h2>Объявление опубликовано!</h2><p>Карточка уже появилась в каталоге Клиентской биржи.</p><div className="success-actions"><a className="ce-secondary" href="/profile?section=client-exchange">Мои объявления</a><a className="ce-primary" href="/client-exchange">Открыть каталог</a></div></div></section>:<>{progress}<section className="wizard-card">{content}</section><footer className="wizard-actions"><button className="ce-secondary" disabled={step===1} onClick={()=>setStep(step-1)}>Назад</button><button className="draft-button" disabled={saving} onClick={()=>save()}>Сохранить черновик</button><button className="ce-primary" disabled={saving} onClick={next}>{step===6?'Опубликовать':'Продолжить'}</button></footer></>}</main><div className={`ce-toast ${toast?'show error':''}`} onClick={()=>setToast('')}>{toast}</div></PublicLayout>}
