import { useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import UserLayout from '../../layouts/UserLayout'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import { getMyAccountingCompany } from '../../api/companies'
import { deleteProfiMarketSolution, getMyProfiMarketSolutions, unpublishProfiMarketSolution } from '../../api/profimarket'
import { deleteClientListing, deleteMyVacancy, getHelpNotifications, getHelpRequests, getMyVacancies, getProfileClientItems, getProfileClientNotifications, markProfileClientNotificationsRead, runClientListingAction, runClientResponseAction, runHelpRequestAction, unpublishMyVacancy, updateProfileName, updateProfilePassword } from '../../api/profile'

const styles=['/static/profile.css','/static/profile-logo.css','/static/profile-sidebar-v2.css','/static/profile-buttons.css','/static/fintalent-theme.css','/static/profile-vacancies.css?v=5','/static/profile-settings.css?v=1','/static/profile-profimarket.css?v=2','/static/profile-profimarket-cover.css?v=1','/static/profile-client-exchange.css?v=1','/static/profile-help.css?v=1','/static/accounting-company.css?v=1']
const date=v=>v?new Date(v).toLocaleDateString('ru-RU'):'—'
const money=v=>v==null?'—':`${new Intl.NumberFormat('ru-RU').format(v)} ₽`
const label=v=>({published:'Опубликовано',draft:'Черновик',archived:'В архиве',active:'Активно',has_responses:'Есть предложения',pending:'На рассмотрении',accepted:'Принято',rejected:'Отклонено',withdrawn:'Отозвано',completed:'Завершено',new:'Новое',PUBLISHED:'Опубликовано',DRAFT:'Черновик'})[v]||v

function Dashboard(){return <section className="welcome-card"><div className="welcome-illustration" aria-hidden="true"><span className="spark spark-one">✦</span><span className="spark spark-two">✧</span><span className="briefcase-shape">▱</span><div className="resume-sheet"><div className="person-shape">●</div><i/><i/><i/><div className="chart-shape"><b/><b/><b/><b/></div><span>✓</span></div><div className="search-shape">⌕</div><div className="donut-shape"/></div><h1>Добро пожаловать в FinTalent!</h1><p>Здесь вы можете создавать резюме, находить вакансии, подбирать сотрудников<br/>и развивать профессиональные навыки.</p><small>Давайте начнём с первого шага.</small><div className="welcome-actions"><Link className="welcome-resume" to="/resume/create"><span>▷</span><div><b>Создать резюме</b><small>Расскажите о своём опыте</small></div><em>→</em></Link><Link className="welcome-vacancy" to="/vacancies/create"><span>▢</span><div><b>Создать вакансию</b><small>Найдите подходящего сотрудника</small></div><em>→</em></Link></div></section>}

function Vacancies(){const[items,setItems]=useState([]),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);getMyVacancies().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);useEffect(load,[load]);async function act(x,a){if(a==='delete'&&!confirm(`Удалить вакансию «${x.title}» навсегда?`))return;try{a==='delete'?await deleteMyVacancy(x.id):await unpublishMyVacancy(x.id);load()}catch(e){setError(e.message)}}const shown=filter==='all'?items:items.filter(x=>x.status===filter);return <section className="my-vacancies-page"><header><div><small>УПРАВЛЕНИЕ ВАКАНСИЯМИ</small><h1>Мои вакансии</h1><p>Все созданные вакансии в одном месте.</p></div><div className="my-vacancies-tools"><label><span>Показывать</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все вакансии</option><option value="published">Только активные</option><option value="draft">Только черновики</option></select></label><Link to="/vacancies/create">＋ Создать вакансию</Link></div></header>{error&&<p className="profile-vacancy-message error visible">{error}</p>}{loading?<div className="my-vacancies-loading">Загружаем вакансии…</div>:shown.length?<><div className="my-vacancies-stats"><span><b>{items.length}</b><small>Всего</small></span><span><b>{items.filter(x=>x.status==='published').length}</b><small>Опубликовано</small></span><span><b>{items.filter(x=>x.status==='draft').length}</b><small>Черновиков</small></span></div><div className="my-vacancies-grid">{shown.map(x=><article className="my-vacancy-card" key={x.id}><header><div className="my-vacancy-icon">▣</div><div><span className={`vacancy-status ${x.status}`}><i/>{label(x.status)}</span><h2>{x.title||'Вакансия'}</h2></div></header><div className="vacancy-card-facts"><span><i>₽</i><b>{x.salary_from==null?'Сумма не указана':`От ${money(x.salary_from)}`}</b></span><span><i>⌖</i><b>{x.city||'Город не указан'}</b></span><span><i>◷</i><b>{date(x.updated_at)}</b></span></div>{x.description&&<p>{x.description}</p>}<footer><Link to={`/vacancies/create?id=${x.id}`}>Редактировать</Link>{x.status==='published'&&<><Link to={`/vacancies/view?id=${x.id}`}>Просмотр</Link><button onClick={()=>act(x,'unpublish')}>Снять с публикации</button></>}<button onClick={()=>act(x,'delete')}>Удалить</button></footer></article>)}</div></>:<div className="my-vacancies-empty"><h2>Пока нет вакансий</h2><Link to="/vacancies/create">Создать вакансию</Link></div>}</section>}

function Settings(){const{user,refresh}=useAuth(),[name,setName]=useState(user?.full_name||''),[message,setMessage]=useState(''),[bad,setBad]=useState(false);const show=(v,e=false)=>{setMessage(v);setBad(e)};async function saveName(e){e.preventDefault();try{const x=await updateProfileName(name);setName(x.full_name);await refresh();show('ФИО успешно обновлено')}catch(x){show(x.message,true)}}async function savePassword(e){e.preventDefault();const f=e.currentTarget;if(f.new_password.value!==f.confirm_password.value)return show('Новые пароли не совпадают',true);try{await updateProfilePassword(f.current_password.value,f.new_password.value);f.reset();show('Пароль успешно изменён')}catch(x){show(x.message,true)}}return <section className="profile-settings-page"><header><small>НАСТРОЙКИ ПРОФИЛЯ</small><h1>Личные данные и безопасность</h1><p>Обновите имя или установите новый пароль.</p></header>{message&&<div className={`settings-message${bad?' error':''}`}>{message}</div>}<div className="settings-grid"><form onSubmit={saveName}><div className="settings-icon">Aa</div><h2>ФИО</h2><p>Используется в профиле, резюме и публикациях.</p><label><span>Фамилия, имя и отчество</span><input value={name} onChange={e=>setName(e.target.value)} maxLength="200" required/></label><button>Сохранить ФИО</button></form><form onSubmit={savePassword}><div className="settings-icon lock">●</div><h2>Смена пароля</h2><label><span>Текущий пароль</span><input name="current_password" type="password" required/></label><label><span>Новый пароль</span><input name="new_password" type="password" minLength="8" maxLength="72" required/></label><label><span>Повторите новый пароль</span><input name="confirm_password" type="password" minLength="8" maxLength="72" required/></label><button>Изменить пароль</button></form></div></section>}

function ProfiMarket(){const[items,setItems]=useState([]),[error,setError]=useState('');const load=useCallback(()=>getMyProfiMarketSolutions().then(x=>setItems(x.items||[])).catch(e=>setError(e.message)),[]);useEffect(load,[load]);async function act(x,a){try{if(a==='delete'){if(!confirm(`Удалить решение «${x.title}»?`))return;await deleteProfiMarketSolution(x.id)}else await unpublishProfiMarketSolution(x.id);load()}catch(e){setError(e.message)}}return <section className="profile-market"><header><div><small>ПРОФИМАРКЕТ</small><h1>Мои решения</h1><p>Создавайте решения и управляйте публикациями.</p></div><Link to="/profimarket/create">＋ Создать решение</Link></header>{error&&<p>{error}</p>}<section className="profile-market-list">{items.length?items.map(x=><article className="profile-market-row" key={x.id}><div className="profile-market-cover"><img src={x.cover_image||'/static/profimarket-package-placeholder.svg'} alt=""/></div><div className="profile-market-info"><small>{x.type==='AI_ASSISTANT'?'ИИ-АССИСТЕНТ И БОТ':'РЕГЛАМЕНТ'}</small><h2>{x.title}</h2><p>{x.short_description}</p></div><div className="profile-market-metric"><small>Статус</small><b>{label(x.status)}</b></div><div className="profile-market-metric"><small>Цена</small><b>{money(x.price)}</b></div><div className="profile-market-actions"><Link to={`/profimarket/create?id=${x.id}`}>Редактировать</Link>{x.status==='PUBLISHED'&&<button onClick={()=>act(x,'unpublish')}>Снять</button>}<button onClick={()=>act(x,'delete')}>Удалить</button></div></article>):<div className="profile-market-empty"><h2>У вас пока нет решений</h2><Link to="/profimarket/create">Создать решение</Link></div>}</section></section>}

function Company(){const[company,setCompany]=useState(),[error,setError]=useState('');useEffect(()=>{getMyAccountingCompany().then(x=>setCompany(x.company)).catch(e=>setError(e.message))},[]);return <section className="ac-profile"><div className="ac-profile-head"><div><span className="ac-kicker">БУХГАЛТЕРСКАЯ КОМПАНИЯ</span><h1>Моя компания</h1><p>Управляйте публичной страницей и компетенциями команды.</p></div><Link className="ac-button" to="/accounting-companies/create">{company?'Редактировать':'Создать страницу'}</Link></div>{error?<div className="ac-empty">{error}</div>:company?<article className="ac-manage-card"><div className="ac-manage-cover" style={company.header_image?{backgroundImage:`url('${company.header_image}')`}:{}}/><div className="ac-manage-body"><div className="ac-manage-main"><div><div className="ac-manage-logo">{company.logo?<img src={company.logo} alt=""/>:company.name?.charAt(0)}</div><h2>{company.name}</h2><p>{company.short_description}</p></div><span className="ac-status">{label(company.status)}</span></div><div className="ac-completeness"><b>Профиль заполнен на {company.completeness}%</b><div className="ac-complete-bar"><i style={{width:`${company.completeness}%`}}/></div></div><Link className="ac-button" to={`/accounting-companies/view?${company.status==='published'?`slug=${encodeURIComponent(company.slug)}`:`id=${company.id}&preview=1`}`}>Просмотр</Link></div></article>:<div className="ac-empty"><h3>У вас ещё нет страницы компании</h3></div>}</section>}

function Help(){const[scope,setScope]=useState('incoming'),[items,setItems]=useState([]),[error,setError]=useState(''),[count,setCount]=useState(0);const load=useCallback(()=>{getHelpRequests(scope).then(setItems).catch(e=>setError(e.message));getHelpNotifications().then(x=>setCount(x.incoming_new||0)).catch(()=>{})},[scope]);useEffect(load,[load]);async function act(id,a){try{await runHelpRequestAction(id,a);load()}catch(e){setError(e.message)}}return <section className="profile-help-page"><header><div><small>ПРОФЕССИОНАЛЬНЫЙ ПРОФИЛЬ</small><h1>Помощь коллегам</h1><p>Входящие обращения и ваши запросы специалистам.</p></div><div className="profile-help-tabs"><button className={scope==='incoming'?'active':''} onClick={()=>setScope('incoming')}>Мне написали {count?`· ${count}`:''}</button><button className={scope==='outgoing'?'active':''} onClick={()=>setScope('outgoing')}>Мои запросы</button></div></header>{error&&<p>{error}</p>}<div className="profile-help-list">{items.length?items.map(x=>{const p=scope==='incoming'?x.requester:x.expert;return <article className="profile-help-card" key={x.id}><header><img src={p?.avatar||'/static/avatar-placeholder.svg'} alt=""/><div><h2>{p?.name}</h2><small>{x.topic?.name} · {date(x.created_at)}</small></div><span className={`help-status ${x.status}`}>{label(x.status)}</span></header><p>{x.text}</p><div className="profile-help-actions">{scope==='incoming'&&x.status==='new'&&<><button className="good" onClick={()=>act(x.id,'accept')}>Принять</button><button className="danger" onClick={()=>act(x.id,'decline')}>Отклонить</button></>}{scope==='incoming'&&x.status==='accepted'&&<button className="good" onClick={()=>act(x.id,'complete')}>Завершить</button>}{scope==='outgoing'&&['new','accepted'].includes(x.status)&&<button className="danger" onClick={()=>act(x.id,'cancel')}>Отменить</button>}</div></article>}):<div className="profile-help-empty">Обращений пока нет</div>}</div></section>}

function ClientExchange(){const[tab,setTab]=useState('listings'),[items,setItems]=useState([]),[error,setError]=useState(''),[unread,setUnread]=useState(0);const load=useCallback(async()=>{try{const x=tab==='notifications'?await getProfileClientNotifications():await getProfileClientItems(tab);setItems(x.items||[]);setUnread(x.unread||0);if(tab==='notifications'&&x.unread)await markProfileClientNotificationsRead()}catch(e){setError(e.message)}},[tab]);useEffect(()=>{load()},[load]);async function act(x,a){if(!confirm('Подтвердите действие'))return;try{if(tab==='listings')a==='delete'?await deleteClientListing(x.id):await runClientListingAction(x.id,a);else await runClientResponseAction(x.id,a);load()}catch(e){setError(e.message)}}const tabs=[['listings','Мои объявления'],['responses','Мои отклики'],['received','Полученные предложения'],['favorites','Избранное'],['notifications',`Уведомления${unread?` · ${unread}`:''}`]];return <section className="ce-profile"><header className="ce-profile-head"><div><small>КЛИЕНТСКАЯ БИРЖА</small><h1>Передача клиентов</h1><p>Управляйте объявлениями и предложениями.</p></div><Link to="/client-exchange/create">＋ Передать клиента</Link></header><nav className="ce-tabs">{tabs.map(([k,v])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{v}</button>)}</nav>{error&&<p>{error}</p>}<div className="ce-profile-list">{items.length?items.map(x=><article className={['listings','favorites'].includes(tab)?'ce-own-card':'ce-response-card'} key={x.id}><header><div><small>{date(x.created_at||x.published_at)}</small><h3>{x.title||x.listing_title||x.buyer_name||x.industry?.name||'Клиент'}</h3></div><span className={`ce-status ${x.status||''}`}>{label(x.status||'')}</span></header>{x.message&&<p>{x.message}</p>}<footer className="ce-own-actions">{tab==='listings'&&<><Link to={`/client-exchange/create?id=${x.id}`}>Изменить</Link>{['draft','archived','cancelled'].includes(x.status)&&<button onClick={()=>act(x,'publish')}>Опубликовать</button>}{['active','has_responses'].includes(x.status)&&<button onClick={()=>act(x,'archive')}>Снять</button>}<button onClick={()=>act(x,'delete')}>Удалить</button></>}{tab==='received'&&x.status==='pending'&&<><button onClick={()=>act(x,'reject')}>Отклонить</button><button onClick={()=>act(x,'accept')}>Выбрать</button></>}{tab==='responses'&&x.status==='pending'&&<button onClick={()=>act(x,'withdraw')}>Отозвать</button>}</footer></article>):<div className="ce-profile-empty"><h3>Данных пока нет</h3></div>}</div></section>}

export default function ProfilePage(){useDocumentPage({title:'Личный кабинет — FinTalent'});usePageStyles(styles);const[p]=useSearchParams(),section=p.get('section')||'profile';const content=section==='vacancies'?<Vacancies/>:section==='settings'?<Settings/>:section==='profimarket'?<ProfiMarket/>:section==='my-company'?<Company/>:section==='client-exchange'?<ClientExchange/>:section==='help'?<Help/>:<Dashboard/>;return <UserLayout active={section}><main className="dashboard-main">{content}</main></UserLayout>}
