import { useState } from 'react'
import Icon from '../../components/Icon'

const meta={AUTOMATION:['Автоматизация','sparkles'],INSTRUCTION:['Инструкция','list'],ONEC_INTEGRATION:['1С Интеграция','calculator'],TEMPLATE:['Шаблон','folder'],CHECKLIST:['Чек-лист','check']}
const money=value=>`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(value||0))} ₽`
const values=value=>Array.isArray(value)?value:[]
function List({items,checks=false}){return <div className={checks?'pmp-check-list':'pmp-value-list'}>{values(items).filter(Boolean).map((item,index)=><div key={`${item}-${index}`}><i>{checks?'□':'✓'}</i><span>{item}</span></div>)}</div>}
function Section({title,children,className=''}){if(!children)return null;return <section className={`pmp-detail-section ${className}`}><h2>{title}</h2>{children}</section>}
function Gallery({solution}){const images=[solution.cover_image,...values(solution.media).filter(x=>x.type==='IMAGE').map(x=>x.url)].filter(Boolean).filter((url,index,all)=>all.indexOf(url)===index),[selectedIndex,setSelectedIndex]=useState(0),selected=images[selectedIndex]||images[0];return <div className="pmp-detail-gallery"><div className="pmp-main-image">{selected?<img src={selected} alt={`${solution.title} — изображение ${Math.min(selectedIndex+1,images.length)}`}/>:<Icon name={meta[solution.type]?.[1]||'folder'}/>}</div>{images.length>1&&<div className="pmp-gallery-thumbnails" aria-label="Изображения решения">{images.map((url,index)=><button type="button" className={`pmp-gallery-thumbnail${index===selectedIndex?' active':''}`} aria-label={`Показать изображение ${index+1}`} aria-pressed={index===selectedIndex} onClick={()=>setSelectedIndex(index)} key={url}><img src={url} alt=""/></button>)}</div>}</div>}
function Author({solution}){return <div className="pmp-detail-author">{solution.author_avatar?<img src={solution.author_avatar} alt=""/>:<i>{(solution.author_name||'А').charAt(0)}</i>}<span><small>Автор продукта</small><b>{solution.author_name||'Автор FinTalent'}</b></span></div>}
function Purchase({solution}){return <aside className="pmp-purchase"><small>Стоимость продукта</small>{solution.old_price&&<del>{money(solution.old_price)}</del>}<strong>{solution.pricing_type==='FREE'?'Бесплатно':money(solution.price)}</strong><button data-buy>Купить</button><p>После оформления продавец получит информацию о заказе и передаст вам материалы.</p><div><span>✓ Безопасное оформление</span><span>✓ Контакт с автором</span><span>✓ Материалы и поддержка</span></div></aside>}
function Common({solution,data}){return <><Section title="О продукте"><p className="pmp-long-copy">{solution.description||solution.short_description}</p></Section>{solution.audiences?.length?<Section title="Кому подойдёт"><div className="pmp-chip-row">{solution.audiences.map(x=><span key={x}>{x}</span>)}</div></Section>:null}<Section title="Что вы получите"><List items={data.included}/></Section><Section title="Автор"><Author solution={solution}/></Section></>}
function Automation({solution,data}){return <><Section title="Что автоматизирует"><p className="pmp-long-copy">{data.process}</p></Section><Section title="Как работает" className="process"><div className="pmp-process">{values(data.steps).map((x,i)=><div key={x}><i>{i+1}</i><span>{x}</span>{i<values(data.steps).length-1&&<b>→</b>}</div>)}</div></Section>{(data.before||data.after)&&<Section title="Что изменится"><div className="pmp-before-after-view"><article><small>БЫЛО</small><p>{data.before}</p></article><i>→</i><article><small>СТАНЕТ</small><p>{data.after}</p></article></div></Section>}<Section title="Совместимость"><div className="pmp-chip-row">{values(data.compatibility).map(x=><span key={x}>{x}</span>)}</div></Section><Section title="Установка"><div className="pmp-specs"><span><small>Сложность</small><b>{data.complexity||'Не указана'}</b></span><span><small>Время внедрения</small><b>{data.implementation_time||'Уточняется'}</b></span><span><small>Требования</small><b>{data.requires_services||'Без дополнительных сервисов'}</b></span></div></Section><Common solution={solution} data={data}/></>}
function Instruction({solution,data}){return <><Common solution={solution} data={{...data,included:[]}}/><Section title="Что внутри"><ol className="pmp-contents">{values(data.contents).map((x,i)=><li key={x}><i>{String(i+1).padStart(2,'0')}</i><span>{x}</span></li>)}</ol></Section><Section title="Фрагмент инструкции"><article className="pmp-document"><small>ПРАКТИЧЕСКАЯ ИНСТРУКЦИЯ</small><h3>{data.excerpt_title||solution.title}</h3><p>{data.excerpt}</p><div className="fade"/><footer>🔒 Это фрагмент материала. Полная инструкция доступна после покупки.</footer></article></Section><Section title="Формат"><div className="pmp-format"><b>{data.format||'PDF'}</b>{data.page_count&&<span>{data.page_count} страниц</span>}{data.updated_at&&<span>обновлено {data.updated_at}</span>}</div></Section><Section title="Что вы получите"><List items={data.included}/></Section></>}
function OneC({solution,data}){return <><Section title="Что умеет"><div className="pmp-feature-grid pmp-onec-features">{values(data.features).map(x=><article key={x}><i><Icon name="check"/></i><b>{x}</b></article>)}</div></Section><Section title="Посмотрите, как работает"><p className="pmp-long-copy">{data.how_works}</p>{data.video_url&&<a className="pmp-video" href={data.video_url} target="_blank" rel="noreferrer"><i>▶</i><span><b>Открыть демонстрацию</b><small>{data.video_url}</small></span></a>}</Section><Section title="Совместимость"><div className="pmp-specs"><span><small>Конфигурации</small><b>{values(data.configurations).join(', ')}</b></span><span><small>Платформа</small><b>{data.platform_version||'Уточняется'}</b></span><span><small>Режим</small><b>{values(data.database_modes).join(' / ')}</b></span></div></Section><Section title="Как происходит установка"><div className="pmp-install">{values(data.installation_steps).map((x,i)=><div key={x}><i>{i+1}</i><span>{x}</span></div>)}</div></Section><Section title="Поддержка"><p className="pmp-long-copy">{data.support||'Условия поддержки уточняются у автора.'}</p></Section><Common solution={solution} data={data}/></>}
function Template({solution,data}){return <><Common solution={solution} data={{...data,included:[]}}/><Section title="Для чего используется"><p className="pmp-long-copy">{data.use_case}</p></Section><Section title="Что внутри"><List items={data.contents}/></Section><Section title="Предпросмотр"><article className="pmp-template-preview"><header><i>▦</i><div><b>{data.file_type||data.format||'Рабочий файл'}</b><small>{data.structure}</small></div></header><p>{data.fragment}</p><div className="pmp-sheet"><i/><i/><i/><i/><i/><i/><i/><i/></div><footer>Реальный фрагмент структуры продукта</footer></article></Section><Section title="Возможности"><List items={data.features}/></Section><Section title="Что вы получите"><List items={data.included}/></Section></>}
function Checklist({solution,data}){const all=values(data.sections).flatMap(x=>values(x.items).map(item=>({section:x.title,item}))),preview=all.slice(0,Number(data.preview_count||5)),hidden=Math.max(0,Number(data.total_items||all.length)-preview.length);return <><div className="pmp-check-metrics"><span><b>{data.total_items||all.length}</b><small>пунктов</small></span><span><b>{data.total_sections||values(data.sections).length}</b><small>разделов</small></span>{data.estimated_minutes&&<span><b>≈ {data.estimated_minutes}</b><small>минут</small></span>}</div><Section title="Что проверяет этот чек-лист"><p className="pmp-long-copy">{data.checks||solution.description}</p></Section><Section title="Содержание"><div className="pmp-check-preview">{preview.map((x,i)=><div key={`${x.item}-${i}`}><small>{x.section}</small><p><i>□</i>{x.item}</p></div>)}{hidden>0&&<footer>🔒 Ещё {hidden} пунктов доступны после покупки</footer>}</div></Section><Common solution={solution} data={data}/></>}

export default function ProfiMarketProductDetail({solution}){const data=solution.product_data||{},Body={AUTOMATION:Automation,INSTRUCTION:Instruction,ONEC_INTEGRATION:OneC,TEMPLATE:Template,CHECKLIST:Checklist}[solution.type];return <div className={`pmp-detail type-${solution.type.toLowerCase()}`}><div className="pmp-breadcrumbs"><a href="/profimarket">ПрофиМаркет</a><i>›</i><span>{meta[solution.type]?.[0]}</span></div><section className="pmp-detail-hero"><Gallery key={solution.id} solution={solution}/><div className="pmp-detail-summary"><span className="pmp-type"><Icon name={meta[solution.type]?.[1]}/>{meta[solution.type]?.[0]}</span><h1>{solution.title}</h1><p>{solution.short_description}</p><Author solution={solution}/><div className="pmp-rating"><b>★ {Number(solution.rating??0).toFixed(1)}</b><span>{solution.review_count||0} оценок</span></div></div><Purchase solution={solution}/></section><div className="pmp-detail-layout"><div>{Body&&<Body solution={solution} data={data}/>}</div><Purchase solution={solution}/></div></div>}
