import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { createProfiMarketSolution, getProfiMarketMeta, getProfiMarketSolution, publishProfiMarketSolution, updateProfiMarketSolution, uploadProfiMarketImage } from '../../api/profimarket'
import Icon from '../../components/Icon'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import PublicLayout from '../../layouts/PublicLayout'

const blank = (type) => ({ type, title: '', short_description: '', description: '', cover_image: '', tags: [], topics: [], audiences: [], ai_features: [], platforms: [], platform_ids: [], media: [], pricing_type: 'MONTHLY', price: 0, old_price: null, trial_days: 0, delivery_type: 'MANUAL', external_url: '', sections: [], access_features: [], key_metrics: [], bonuses: [], crm_ids: [] })
const steps = ['Основная информация', 'Что умеет', 'Где работает', 'Демо и изображения', 'Цена и trial', 'Получение доступа', 'Предпросмотр', 'Публикация']
const field = (event) => event.target.type === 'number' ? Number(event.target.value) : event.target.value

function TypeChoice({ choose, busy }) {
  return <div className="pm-create-shell"><div className="pm-create-head"><a href="/profimarket">← Вернуться в ПрофиМаркет</a><span><i>✓</i> Единый кабинет FinTalent</span></div><section className="pm-type-choice"><small>НОВОЕ РЕШЕНИЕ</small><h1>Что вы хотите разместить на ПрофиМаркете?</h1><p>Для каждого типа решения подготовлен отдельный профессиональный мастер.</p><div className="pm-type-grid"><button disabled={busy} className="pm-type-option regulation" onClick={() => choose('REGULATION')}><i><Icon name="workflow" /></i><h2>Регламент</h2><p>Готовый рабочий процесс, который можно внедрить в CRM.</p><strong>Выбрать регламент →</strong></button><button disabled={busy} className="pm-type-option ai" onClick={() => choose('AI_ASSISTANT')}><i><Icon name="bot" /></i><h2>ИИ-ассистент или бот</h2><p>ИИ-инструмент, бот или помощник для автоматизации работы.</p><strong>Выбрать ИИ-инструмент →</strong></button></div></section></div>
}

function Basic({ value, change, upload }) {
  return <><header><small>ШАГ 1</small><h1>Основная информация</h1><p>Расскажите, какую профессиональную задачу решает ваше решение.</p></header><div className="pm-form-grid"><label className="pm-field wide">Название<input value={value.title} onChange={change('title')} /></label><label className="pm-field wide">Короткое описание<textarea rows="3" value={value.short_description} onChange={change('short_description')} /></label><label className="pm-field wide">Полное описание<textarea rows="6" value={value.description} onChange={change('description')} /></label><label className="pm-field wide">Обложка<div className="pm-upload-box">{value.cover_image ? <img src={value.cover_image} alt="Обложка" /> : <span><b>Загрузить обложку</b><small>JPG, PNG или WebP до 7 МБ</small></span>}<input type="file" accept="image/*" onChange={(event) => upload(event.target.files[0], 'cover')} /></div></label>{[['tags','Теги через запятую'],['topics','Тематика через запятую'],['audiences','Для кого предназначено']].map(([name,label]) => <label className="pm-field" key={name}>{label}<input value={(value[name] || []).join(', ')} onChange={(event) => change(name)({ target: { value: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) } })} /></label>)}</div></>
}

function Features({ items, setItems }) {
  return <><header><small>ВОЗМОЖНОСТИ</small><h1>Что умеет помощник</h1><p>Добавьте ключевые возможности ИИ-инструмента.</p></header><div className="pm-repeat-list">{items.map((item, index) => <article className="pm-repeat-item" key={index}><button className="pm-remove" onClick={() => setItems(items.filter((_, i) => i !== index))}>×</button><div className="pm-form-grid"><label className="pm-field">Заголовок<input value={item.title} onChange={(event) => setItems(items.map((x, i) => i === index ? { ...x, title: event.target.value } : x))} /></label><label className="pm-field">Подпись<input value={item.description} onChange={(event) => setItems(items.map((x, i) => i === index ? { ...x, description: event.target.value } : x))} /></label></div></article>)}</div><button className="pm-add" onClick={() => setItems([...items, { icon: 'sparkles', title: '', description: '', sort_order: items.length }])}>＋ Добавить возможность</button></>
}

function Platforms({ meta, selected, setSelected }) {
  return <><header><small>СПРАВОЧНИК</small><h1>Где работает помощник</h1><p>Можно выбрать несколько платформ.</p></header><div className="pm-check-grid">{(meta.platforms || []).map((item) => <label className="pm-choice-check" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(selected.includes(item.id) ? selected.filter((id) => id !== item.id) : [...selected, item.id])} /><Icon name={item.code === 'telegram' ? 'telegram' : 'cloud'} /><span><b>{item.name}</b><small>{item.code}</small></span></label>)}</div></>
}

function Media({ value, change, upload, remove }) {
  return <><header><small>ПРОДАЮЩАЯ ДЕМОНСТРАЦИЯ</small><h1>Видео и изображения</h1><p>Добавьте video URL и скриншоты.</p></header><div className="pm-form-grid"><label className="pm-field wide">URL демонстрационного видео<input type="url" value={(value.media.find((item) => item.type === 'VIDEO') || {}).url || ''} onChange={(event) => change(event.target.value)} /></label><label className="pm-field wide">Добавить скриншот<div className="pm-upload-box"><span><b>Загрузить изображение</b><small>Можно добавить несколько последовательно</small></span><input type="file" accept="image/*" onChange={(event) => upload(event.target.files[0], 'media')} /></div></label></div><div className="pm-thumbnails">{value.media.filter((item) => item.type === 'IMAGE').map((item) => <span key={item.url}><img src={item.url} alt="" /><button onClick={() => remove(item)}>×</button></span>)}</div></>
}

export default function ProfiMarketCreatePage() {
  usePageStyles(['/static/profimarket.css?v=1']); useDocumentPage({ title: 'Разместить решение — ПрофиМаркет' })
  const [params] = useSearchParams(), editID = params.get('id'), [solution, setSolution] = useState(null), [meta, setMeta] = useState({}), [step, setStep] = useState(0), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState('')
  useEffect(() => { Promise.all([getProfiMarketMeta(), editID ? getProfiMarketSolution(editID) : null]).then(([dictionary, current]) => { setMeta(dictionary); if (current?.type === 'REGULATION') window.location.replace(`/profimarket/regulation/edit?id=${current.id}`); else if (current) setSolution({ ...current, platform_ids: (current.platforms || []).map((item) => item.id), ai_features: current.ai_features || [], media: current.media || [] }) }).catch((requestError) => setError(requestError.message)) }, [editID])
  const change = (name) => (event) => setSolution((value) => ({ ...value, [name]: field(event) }))
  async function choose(type) { setBusy(true); try { const created = await createProfiMarketSolution(blank(type)); if (type === 'REGULATION') window.location.replace(`/profimarket/regulation/edit?id=${created.id}`); else window.location.replace(`/profimarket/create?id=${created.id}`) } catch (requestError) { setError(requestError.message); setBusy(false) } }
  function payload() { return { ...blank(solution.type), ...solution, old_price: solution.old_price || null, ai_features: solution.ai_features.map((item, index) => ({ ...item, sort_order: index })), media: solution.media.map((item, index) => ({ ...item, sort_order: index })), platform_ids: solution.platform_ids } }
  async function save() { setBusy(true); try { const saved = await updateProfiMarketSolution(solution.id, payload()); setSolution({ ...saved, platform_ids: (saved.platforms || []).map((item) => item.id), ai_features: saved.ai_features || [], media: saved.media || [] }); setNotice('Черновик сохранён'); return true } catch (requestError) { setError(requestError.message); return false } finally { setBusy(false) } }
  async function move(next) { if (await save()) setStep(next) }
  async function upload(file, kind) { if (!file) return; setBusy(true); try { const data = await uploadProfiMarketImage(file); if (kind === 'cover') setSolution((value) => ({ ...value, cover_image: data.url })); else setSolution((value) => ({ ...value, media: [...value.media, { type: 'IMAGE', url: data.url, is_preview: !value.media.length }] })) } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  async function publish() { if (!await save()) return; try { await publishProfiMarketSolution(solution.id); window.location.assign(`/profimarket/solution/${solution.slug}`) } catch (requestError) { setError(requestError.message) } }
  if (error && !solution && editID) return <PublicLayout><main className="pm-create-page"><div className="pm-loading">{error}</div></main></PublicLayout>
  if (!solution) return <PublicLayout><main className="pm-create-page">{error && <div className="pm-notice bad">{error}</div>}<TypeChoice choose={choose} busy={busy} /></main></PublicLayout>
  let content
  if (step === 0) content = <Basic value={solution} change={change} upload={upload} />
  else if (step === 1) content = <Features items={solution.ai_features} setItems={(items) => setSolution({ ...solution, ai_features: items })} />
  else if (step === 2) content = <Platforms meta={meta} selected={solution.platform_ids} setSelected={(platform_ids) => setSolution({ ...solution, platform_ids })} />
  else if (step === 3) content = <Media value={solution} change={(url) => setSolution({ ...solution, media: [...solution.media.filter((item) => item.type !== 'VIDEO'), ...(url ? [{ type: 'VIDEO', url, is_preview: true }] : [])] })} upload={upload} remove={(target) => setSolution({ ...solution, media: solution.media.filter((item) => item !== target) })} />
  else if (step === 4) content = <><header><small>МОНЕТИЗАЦИЯ</small><h1>Цена и пробный период</h1></header><div className="pm-form-grid"><label className="pm-field">Модель оплаты<select value={solution.pricing_type} onChange={change('pricing_type')}><option value="ONE_TIME">Разовая покупка</option><option value="MONTHLY">Цена в месяц</option><option value="YEARLY">Цена в год</option><option value="FREE">Бесплатно</option></select></label>{[['price','Цена, ₽'],['old_price','Старая цена, ₽'],['trial_days','Пробный период, дней']].map(([name,label]) => <label className="pm-field" key={name}>{label}<input type="number" value={solution[name] || ''} onChange={change(name)} /></label>)}</div></>
  else if (step === 5) content = <><header><small>ПОЛУЧЕНИЕ ДОСТУПА</small><h1>Как покупатель получит решение</h1></header><div className="pm-form-grid"><label className="pm-field">Способ подключения<select value={solution.delivery_type} onChange={change('delivery_type')}><option value="LINK">Ссылка</option><option value="MANUAL">Автор подключает вручную</option></select></label><label className="pm-field">Ссылка на инструмент<input type="url" value={solution.external_url} onChange={change('external_url')} /></label></div></>
  else if (step === 6) content = <><header><small>ПРОВЕРКА</small><h1>Посмотреть глазами покупателя</h1></header><div className="pm-preview-summary"><div><h2>{solution.title || 'Название ещё не заполнено'}</h2><p>{solution.short_description}</p><a className="pm-add" href={`/profimarket/solution/${solution.id}?preview=1`} target="_blank" rel="noreferrer">Открыть страницу покупателя ↗</a></div></div></>
  else content = <><header><small>ФИНАЛЬНЫЙ ШАГ</small><h1>Всё готово к публикации</h1></header><div className="pm-publish-box"><i><Icon name="check" /></i><div><b>Проверьте обязательные разделы</b><p>Нужны название, описание и хотя бы одна возможность.</p></div></div><button className="pm-buy" disabled={!solution.title || !solution.short_description || !solution.ai_features.length || busy} onClick={publish}>Опубликовать решение →</button></>
  return <PublicLayout><main className="pm-create-page"><div className="pm-create-shell"><div className="pm-create-head"><a href="/profimarket/my">← Мои решения</a><span><i>✓</i><b>{notice || 'Черновик сохранён'}</b></span></div><div className="pm-editor-layout"><aside className="pm-wizard-nav"><small>ИИ-АССИСТЕНТ</small>{steps.map((label, index) => <button className={index === step ? 'active' : ''} key={label} onClick={() => move(index)}><i>{index + 1}</i>{label}</button>)}</aside><div><section className="pm-editor-card">{content}</section><footer className="pm-editor-footer"><span>{step + 1} из {steps.length} · {solution.status === 'PUBLISHED' ? 'Опубликовано' : 'Черновик'}</span>{step > 0 && <button className="secondary" onClick={() => move(step - 1)}>← Назад</button>}<button className="secondary" disabled={busy} onClick={save}>Сохранить</button>{step < steps.length - 1 && <button className="primary" disabled={busy} onClick={() => move(step + 1)}>Продолжить →</button>}</footer></div></div></div>{error && <div className="pm-notice bad">{error}</div>}</main></PublicLayout>
}
