ALTER TABLE test_attempt_answers ADD COLUMN IF NOT EXISTS answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE test_attempt_answers ADD COLUMN IF NOT EXISTS response_seconds INTEGER NOT NULL DEFAULT 0;
