DO $seed$
DECLARE author_id BIGINT; reader_id BIGINT; pub_id BIGINT; cat_id BIGINT; series_id BIGINT; linked_test BIGINT;
BEGIN
 SELECT id INTO author_id FROM users WHERE email='publications.demo@fintalent.local';
 IF author_id IS NULL THEN
   INSERT INTO users(full_name,email,password_hash,agreed_to_terms,avatar_url)
   SELECT 'Ирина Петрова','publications.demo@fintalent.local',password_hash,TRUE,'/static/profile-3-avatar.png' FROM users ORDER BY id LIMIT 1 RETURNING id INTO author_id;
 END IF;
 IF author_id IS NULL THEN RETURN; END IF;
 SELECT id INTO reader_id FROM users WHERE id<>author_id ORDER BY id LIMIT 1;
 SELECT id INTO cat_id FROM publication_categories WHERE slug='nalogi-i-otchetnost';
 SELECT id INTO linked_test FROM tests WHERE status='published' ORDER BY id LIMIT 1;
 INSERT INTO publication_series(author_id,title,slug,description,status) VALUES(author_id,'УСН с нуля','usn-s-nulya','Практическая серия о переходе, учёте и отчётности на УСН.','published') ON CONFLICT(slug) DO UPDATE SET status='published' RETURNING id INTO series_id;
 INSERT INTO publications(author_id,category_id,title,subtitle,excerpt,cover_image,content_json,content_html,summary_points,slug,seo_title,seo_description,status,visibility,moderation_status,relevance_status,difficulty,language,reading_time,allow_comments,is_recommended,editor_mark,published_at,last_relevance_check_at,next_relevance_check_at,updated_at)
 VALUES(author_id,cat_id,'5 ошибок при переходе на УСН в 2025 году','Практический разбор для бухгалтеров и владельцев бизнеса','Разбираем частые ошибки при переходе на упрощённую систему налогообложения и способы снизить налоговые риски.','/static/publication-usn-cover.png',
 '[{"type":"h2","text":"1. Неправильная оценка доходов"},{"type":"paragraph","text":"Самая распространённая ошибка — некорректная оценка доходов за девять месяцев. Если фактический доход превысит лимит, организация может утратить право на применение УСН с начала квартала, в котором допущено превышение."},{"type":"avoid","text":"Регулярно отслеживайте доходы в течение года, учитывайте все поступления и используйте консервативный прогноз с запасом."},{"type":"h2","text":"2. Пропуск срока подачи уведомления"},{"type":"paragraph","text":"Уведомление о переходе на УСН подаётся в установленный законом срок. Пропуск срока означает, что применять специальный режим сразу не получится."},{"type":"avoid","text":"Подготовьте уведомление заранее, проверьте подтверждение получения и сохраните его вместе с учётными документами."},{"type":"h2","text":"3. Неверный выбор объекта налогообложения"},{"type":"paragraph","text":"Объекты «доходы» и «доходы минус расходы» дают разную нагрузку. Решение следует принимать после расчёта нескольких сценариев, а не по общей рекомендации."},{"type":"example","text":"Сравните налог при реалистичной доле подтверждённых расходов и учтите минимальный налог."},{"type":"h2","text":"4. Расходы без подтверждающих документов"},{"type":"paragraph","text":"Для уменьшения налоговой базы расходы должны соответствовать требованиям, быть экономически обоснованными и документально подтверждёнными."},{"type":"note","text":"Заранее настройте проверку первичных документов и перечень допустимых расходов."},{"type":"h2","text":"5. Отсутствие переходного чек-листа"},{"type":"paragraph","text":"Переход затрагивает договоры, учётную политику, кассу, первичные документы и отчётность. Без единого плана легко пропустить зависимую задачу."},{"type":"checklist","items":["Проверить лимиты и ограничения","Выбрать объект налогообложения","Подать уведомление","Обновить учётную политику","Проверить договоры и кассу"]},{"type":"conclusion","text":"Переход на УСН безопаснее проводить как отдельный проект: с расчётами, ответственными, сроками и финальной проверкой."}]'::jsonb,
 '', '["Проверьте лимиты доходов и ограничения до подачи уведомления.","Сравните оба объекта налогообложения на реальных данных.","Соберите подтверждающие документы и переходный чек-лист.","Зафиксируйте контрольные даты и ответственных."]'::jsonb,
 '5-oshibok-pri-perehode-na-usn-v-2025-godu','5 ошибок при переходе на УСН — разбор бухгалтера','Практический разбор пяти ошибок при переходе на УСН: сроки, лимиты, расходы, объект налогообложения и чек-лист.','published','public','published','current','medium','ru',9,TRUE,TRUE,TRUE,NOW()-INTERVAL '18 days',NOW()-INTERVAL '2 days',NOW()+INTERVAL '6 months',NOW()-INTERVAL '2 days')
 ON CONFLICT(slug) DO UPDATE SET content_json=EXCLUDED.content_json,summary_points=EXCLUDED.summary_points,cover_image=EXCLUDED.cover_image,status='published',visibility='public',updated_at=EXCLUDED.updated_at RETURNING id INTO pub_id;
 UPDATE publications SET content_html=(SELECT string_agg(CASE b->>'type' WHEN 'h2' THEN '<h2>'||(b->>'text')||'</h2>' WHEN 'paragraph' THEN '<p>'||(b->>'text')||'</p>' WHEN 'avoid' THEN '<aside class="article-callout avoid"><b>Как избежать</b><p>'||(b->>'text')||'</p></aside>' WHEN 'example' THEN '<aside class="article-callout example"><b>Практический пример</b><p>'||(b->>'text')||'</p></aside>' WHEN 'note' THEN '<aside class="article-callout note"><b>Обратите внимание</b><p>'||(b->>'text')||'</p></aside>' WHEN 'conclusion' THEN '<aside class="article-callout conclusion"><b>Вывод</b><p>'||(b->>'text')||'</p></aside>' ELSE '' END,'') FROM jsonb_array_elements(content_json)b) WHERE id=pub_id;
 INSERT INTO publication_series_items VALUES(series_id,pub_id,4) ON CONFLICT(publication_id) DO UPDATE SET series_id=EXCLUDED.series_id,sort_order=4;
 INSERT INTO publication_tags(name,slug) VALUES('УСН','usn'),('Налоги','nalogi'),('Малый бизнес','malyy-biznes'),('Отчётность','otchetnost') ON CONFLICT(slug) DO NOTHING;
 INSERT INTO publication_tag_links SELECT pub_id,id FROM publication_tags WHERE slug IN('usn','nalogi','malyy-biznes','otchetnost') ON CONFLICT DO NOTHING;
 INSERT INTO publication_topic_links SELECT pub_id,id FROM publication_topics WHERE slug='usn' ON CONFLICT DO NOTHING;
 INSERT INTO publication_skill_links SELECT pub_id,i.id,1 FROM dictionary_items i WHERE lower(i.value) LIKE '%усн%' OR lower(i.value) LIKE '%отчет%' OR lower(i.value) LIKE '%отчёт%' LIMIT 6 ON CONFLICT DO NOTHING;
 IF linked_test IS NOT NULL THEN INSERT INTO publication_test_links VALUES(pub_id,linked_test,0) ON CONFLICT DO NOTHING; END IF;
 INSERT INTO publication_versions(publication_id,version,changed_by,title,excerpt,content_json,content_html,change_summary,change_reason,status) VALUES
 (pub_id,1,author_id,'5 ошибок при переходе на УСН в 2025 году','Первая версия', (SELECT content_json FROM publications WHERE id=pub_id),(SELECT content_html FROM publications WHERE id=pub_id),'Первая редакция','created','previous'),
 (pub_id,2,author_id,'5 ошибок при переходе на УСН в 2025 году','Обновление', (SELECT content_json FROM publications WHERE id=pub_id),(SELECT content_html FROM publications WHERE id=pub_id),'Обновлены сроки и добавлен чек-лист','rules_changed','current') ON CONFLICT DO NOTHING;
 IF reader_id IS NOT NULL THEN
  INSERT INTO publication_comments(publication_id,author_id,message_type,body) SELECT pub_id,reader_id,'question','Если компания превысила лимит уже после перехода, с какого момента нужно пересчитать налоги?' WHERE NOT EXISTS(SELECT 1 FROM publication_comments pc WHERE pc.publication_id=pub_id AND pc.author_id=reader_id AND pc.message_type='question');
  INSERT INTO publication_comments(publication_id,author_id,parent_id,message_type,body,is_best,is_confirmed) SELECT pub_id,(SELECT p.author_id FROM publications p WHERE p.id=pub_id),c.id,'answer','Пересчёт зависит от периода, в котором произошло превышение. Проверьте дату превышения и действующие на этот период правила. Рекомендую зафиксировать расчёт отдельной справкой. ',TRUE,TRUE FROM publication_comments c WHERE c.publication_id=pub_id AND c.author_id=reader_id AND NOT EXISTS(SELECT 1 FROM publication_comments a WHERE a.publication_id=pub_id AND a.author_id=(SELECT p.author_id FROM publications p WHERE p.id=pub_id) AND a.parent_id=c.id) ORDER BY c.id LIMIT 1;
 END IF;
 INSERT INTO publication_analytics_daily(publication_id,day,views,unique_views,profile_clicks,test_clicks,test_completions,new_followers,citations) VALUES(pub_id,CURRENT_DATE-1,420,371,18,37,12,9,3), (pub_id,CURRENT_DATE,184,161,7,14,4,3,1) ON CONFLICT DO NOTHING;
END $seed$;
