UPDATE client_exchange_dictionary_items AS item
SET icon = icons.icon, updated_at = NOW()
FROM (VALUES
    ('online_stores','/static/icons/client-exchange/industries/online_stores.svg'),
    ('retail','/static/icons/client-exchange/industries/retail.svg'),
    ('wholesale','/static/icons/client-exchange/industries/wholesale.svg'),
    ('wholesale_retail','/static/icons/client-exchange/industries/wholesale_retail.svg'),
    ('marketplaces','/static/icons/client-exchange/industries/marketplaces.svg'),
    ('manufacturing','/static/icons/client-exchange/industries/manufacturing.svg'),
    ('construction','/static/icons/client-exchange/industries/construction.svg'),
    ('repair','/static/icons/client-exchange/industries/repair.svg'),
    ('real_estate','/static/icons/client-exchange/industries/real_estate.svg'),
    ('management_companies','/static/icons/client-exchange/industries/management_companies.svg'),
    ('utilities','/static/icons/client-exchange/industries/utilities.svg'),
    ('transport','/static/icons/client-exchange/industries/transport.svg'),
    ('cargo','/static/icons/client-exchange/industries/cargo.svg'),
    ('logistics','/static/icons/client-exchange/industries/logistics.svg'),
    ('courier','/static/icons/client-exchange/industries/courier.svg'),
    ('car_service','/static/icons/client-exchange/industries/car_service.svg'),
    ('car_dealers','/static/icons/client-exchange/industries/car_dealers.svg'),
    ('it','/static/icons/client-exchange/industries/it.svg'),
    ('software','/static/icons/client-exchange/industries/software.svg'),
    ('saas','/static/icons/client-exchange/industries/saas.svg'),
    ('marketing','/static/icons/client-exchange/industries/marketing.svg'),
    ('consulting','/static/icons/client-exchange/industries/consulting.svg'),
    ('legal','/static/icons/client-exchange/industries/legal.svg'),
    ('education','/static/icons/client-exchange/industries/education.svg'),
    ('online_schools','/static/icons/client-exchange/industries/online_schools.svg'),
    ('medical','/static/icons/client-exchange/industries/medical.svg'),
    ('dentistry','/static/icons/client-exchange/industries/dentistry.svg'),
    ('beauty','/static/icons/client-exchange/industries/beauty.svg'),
    ('fitness','/static/icons/client-exchange/industries/fitness.svg'),
    ('restaurants','/static/icons/client-exchange/industries/restaurants.svg'),
    ('catering','/static/icons/client-exchange/industries/catering.svg'),
    ('hotels','/static/icons/client-exchange/industries/hotels.svg'),
    ('tourism','/static/icons/client-exchange/industries/tourism.svg'),
    ('agriculture','/static/icons/client-exchange/industries/agriculture.svg'),
    ('food','/static/icons/client-exchange/industries/food.svg'),
    ('light_industry','/static/icons/client-exchange/industries/light_industry.svg'),
    ('import','/static/icons/client-exchange/industries/import.svg'),
    ('export','/static/icons/client-exchange/industries/export.svg'),
    ('foreign_trade','/static/icons/client-exchange/industries/foreign_trade.svg'),
    ('finance','/static/icons/client-exchange/industries/finance.svg'),
    ('insurance','/static/icons/client-exchange/industries/insurance.svg'),
    ('rental','/static/icons/client-exchange/industries/rental.svg'),
    ('cleaning','/static/icons/client-exchange/industries/cleaning.svg'),
    ('security','/static/icons/client-exchange/industries/security.svg'),
    ('hr','/static/icons/client-exchange/industries/hr.svg'),
    ('creative','/static/icons/client-exchange/industries/creative.svg'),
    ('bloggers','/static/icons/client-exchange/industries/bloggers.svg'),
    ('ngo','/static/icons/client-exchange/industries/ngo.svg'),
    ('franchise','/static/icons/client-exchange/industries/franchise.svg'),
    ('other_services','/static/icons/client-exchange/industries/other_services.svg')
) AS icons(code,icon)
WHERE item.kind = 'industry'
  AND item.code = icons.code
  AND (BTRIM(item.icon) = '' OR BTRIM(item.icon) ~ '^\?+$');
