import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { finishEmployeeTest, getEmployeeTest, saveEmployeeTestAnswer, startEmployeeTest } from '../../api/tests'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import QuestionChat from '../../components/tests/QuestionChat'

const styles=['/static/employee-test.css?v=1','/static/employee-test-start.css?v=6','/static/test-chat.css','/static/test-chat-question.css','/static/test-chat-click.css','/static/test-chat-fade.css','/static/test-user-answer.css','/static/employee-test-chat.css?v=5']
function Intro({info,start,busy}){return <section className="et-public-intro"><div className="et-public-brand"><i><img src="/static/logo.png" alt="FinTalent"/></i><span><b>Fin <em>Talent</em></b><small>Профессиональное тестирование</small></span></div><div className="et-public-visual" aria-hidden="true"><span className="et-visual-sheet"><i>✓</i><b/><b/><b/></span><span className="et-visual-chart"><i/><i/><i/><i/></span><em>✦</em></div><div className="et-public-copy"><div className="et-public-mark">✓</div><small>ПЕРСОНАЛЬНОЕ ТЕСТИРОВАНИЕ</small><h1>{info.test_title}</h1><p>Здравствуйте, <b>{info.employee_name}</b>. Эта ссылка создана персонально для вас.</p><div className="et-public-facts"><span><b>{info.question_count}</b><small>вопросов</small></span><span><b>{info.time_limit_seconds?Math.round(info.time_limit_seconds/60):'Без лимита'}</b><small>{info.time_limit_seconds?'минут':'времени'}</small></span></div><p className="et-public-warning"><b>Важно:</b> после начала тест уже нельзя остановить и продолжить позже.</p><button className="fintalent-test-button" disabled={busy} onClick={start}><span className="fintalent-test-button__text">{busy?'Запускаем…':info.status==='started'?'Продолжить тест':'Пройти тестирование'}</span><span className="fintalent-test-button__action"><span className="fintalent-test-button__circle">→</span></span></button><em className="et-public-note">Не закрывайте страницу во время прохождения. Ответы сохраняются после каждого вопроса.</em></div></section>}
function Chat({info,token,initial,done,fail}){return <QuestionChat employee title={info.test_title} questions={info.questions} initialIndex={initial} startedAt={info.attempt_started_at} remainingSeconds={info.remaining_seconds} timeLimitSeconds={info.time_limit_seconds} saveAnswer={body=>saveEmployeeTestAnswer(token,body)} finish={()=>finishEmployeeTest(token)} onDone={done} onError={fail}/>}
export default function EmployeeTestPage(){usePageStyles(styles);const [params]=useSearchParams(),token=params.get('token')||'',[info,setInfo]=useState(),[running,setRunning]=useState(false),[finished,setFinished]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);useDocumentPage({title:info?.test_title||'Тестирование'});useEffect(()=>{getEmployeeTest(token).then(value=>{setInfo(value);if(value.status==='finished')setFinished(true)}).catch(e=>setError(e.message))},[token]);async function start(){setBusy(true);try{if(info.status!=='started')await startEmployeeTest(token);const value=await getEmployeeTest(token);setInfo(value);const answered=new Set(value.answered_question_ids||[]);if(value.questions.length&&value.questions.every(question=>answered.has(question.id))){await finishEmployeeTest(token);setFinished(true);return}setRunning(true);history.pushState({employeeTest:'running'},'',`${location.pathname}${location.search}#test`)}catch(e){setError(e.message)}finally{setBusy(false)}}if(error)return <main id="employee-test"><section className="et-public-result error"><h1>Ссылка недоступна</h1><p>{error}</p><div>Попросите организатора отправить новую персональную ссылку.</div></section></main>;if(!info)return <main id="employee-test"><div className="employee-test-loading">Загружаем тест…</div></main>;if(finished)return <main id="employee-test"><section className="et-public-result"><div className="et-public-mark">✓</div><h1>Тест завершён</h1><p>Ваш результат сохранён и доступен организатору.</p></section></main>;const answered=new Set(info.answered_question_ids||[]),initial=Math.max(0,info.questions.findIndex(q=>!answered.has(q.id)));return <main id="employee-test">{running?<Chat info={info} token={token} initial={initial} done={()=>setFinished(true)} fail={setError}/>:<Intro info={info} start={start} busy={busy}/>}</main>}
