import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { finishTestAttempt, getTest, getTestAttempt, getTestReviews, saveTestAnswer, startTestAttempt } from '../../api/tests'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import UserLayout from '../../layouts/UserLayout'
import QuestionChat from '../../components/tests/QuestionChat'

const styles=['/static/profile.css','/static/test-chat-profile.css','/static/profile-logo.css','/static/profile-sidebar-v2.css','/static/profile-buttons.css','/static/test-chat.css','/static/test-chat-question.css','/static/test-chat-click.css','/static/test-chat-fade.css','/static/test-chat-history.css','/static/test-answer-review.css','/static/test-user-answer.css','/static/test-start.css','/static/test-start-reviews.css','/static/fintalent-theme.css']
const duration=s=>{s=Math.max(0,Math.round(s||0));return s<60?`${s} сек.`:`${Math.floor(s/60)} мин. ${s%60} сек.`}
const grouped=a=>(a||[]).reduce((m,x)=>{const v=m.get(x.question_id)||{...x,ids:[],names:[]};if(x.selected_answer_id)v.ids.push(x.selected_answer_id);if(x.selected_answer)v.names.push(x.selected_answer);m.set(x.question_id,v);return m},new Map())

function Review({result}){const answers=grouped(result.answers),questions=result.questions||[];return <section className="answer-review history-review"><div className="review-heading"><div><span>Разбор результатов</span><h2>Проверьте свои ответы</h2></div><b>{questions.filter(q=>answers.get(q.id)?.is_correct).length}<small> / {questions.length}</small></b></div><div className="review-list">{questions.map((q,i)=>{const a=answers.get(q.id),selected=new Set(a?.ids||[]),correct=a?.is_correct===true;return <article key={q.id} className={`review-question ${correct?'correct':'wrong'}`}><header><span>{correct?'✓':'×'}</span><div><small>Вопрос {i+1}</small><h3>{q.question}</h3></div><b>{correct?'Верно':'Есть ошибка'}</b></header>{q.question_type==='text'?<div className="text-comparison"><div><small>Ваш ответ</small><p>{a?.text_answer||'Ответ не дан'}</p></div></div>:<ul>{q.answers.map(x=><li key={x.id} className={x.is_correct?'right-answer':selected.has(x.id)?'wrong-answer':''}><i>{x.is_correct?'✓':selected.has(x.id)?'×':''}</i><span>{x.answer}</span></li>)}</ul>}{q.explanation&&<p className="review-explanation">{q.explanation}</p>}</article>})}</div></section>}
function Result({value}){const [show,setShow]=useState(false);return <><div className="bot-message result-message"><b>Тест завершён</b><div className="result-percent">{Math.round(value.percent)}%</div><h2>{value.passed?'Отличный результат!':'Результат сохранён'}</h2><p>{value.score} из {value.max_score} баллов · общее время {duration(value.duration_seconds)}</p>{!show&&<button className="show-review" onClick={()=>setShow(true)}>Проверить ответы <span>↓</span></button>}<a href="/tests">Вернуться к тестам</a></div>{show&&<Review result={value}/>}</>}
function Start({test,reviews,start,busy,error}){const rating=reviews.length?reviews.reduce((s,x)=>s+Number(x.rating),0)/reviews.length:0;return <section className="test-start-screen"><div className="test-start-layout"><div className="test-start-card"><a className="test-start-back" href="/marketplace">← Вернуться к тестам</a><div className="test-start-icon">✓</div><span className="test-start-eyebrow">Профессиональное тестирование</span><h1>{test.title}</h1><div className="test-author"><i>{(test.author_name||'F').charAt(0)}</i><span><small>Автор теста</small><b>{test.author_name||'Команда FinTalent'}</b></span></div><p>{test.description}</p><div className="test-start-metrics"><div><i>◷</i><b>{test.time_limit_seconds?`${Math.ceil(test.time_limit_seconds/60)} минут`:'Без ограничения'}</b><small>Время на прохождение</small></div><div><i>▤</i><b>{test.questions?.length||0}</b><small>Количество вопросов</small></div><div><i>◎</i><b>{Math.round(test.average_percent||0)}%</b><small>Средний результат</small></div></div><div className={`test-start-note ${error?'error':''}`}><span>!</span><p>{error||'После начала теста запустится таймер. Вернуться к предыдущему вопросу нельзя.'}</p></div><button disabled={busy} onClick={start}>{busy?'Запускаем тест…':'Начать тест'} <span>→</span></button></div><aside className="test-reviews"><header><div><span>Отзывы</span><h2>Что говорят пользователи</h2></div><b>{rating.toFixed(1)}<small>★★★★★</small><em>{reviews.length} отзывов</em></b></header><div className="review-scroll">{reviews.map(x=><article key={x.id}><div><i>{x.author.charAt(0)}</i><span><b>{x.author}</b></span><strong>{'★'.repeat(x.rating)}</strong></div><p>{x.comment}</p></article>)}</div></aside></div></section>}
function Chat({test,attempt,done}){return <QuestionChat title={test.title} questions={test.questions} startedAt={attempt.started_at} saveAnswer={body=>saveTestAnswer(attempt.id,body)} finish={()=>finishTestAttempt(attempt.id)} onDone={done}/>}
function History({value}){return <div className="chat-shell history"><div className="chat-top"><a href="/tests">←</a><div className="chat-avatar">FT</div><div><h1>{value.test_title}</h1><p>Сохранённая переписка</p></div><div className="chat-progress"><b>{Math.round(value.percent)}%</b></div></div><div className="chat-messages"><Result value={value}/><Review result={value}/></div></div>}
export default function TestTakePage(){useDocumentPage({title:'Прохождение теста — FinTalent'});usePageStyles(styles);const [p]=useSearchParams(),id=Number(p.get('id')),old=Number(p.get('attempt')),[test,setTest]=useState(),[reviews,setReviews]=useState([]),[attempt,setAttempt]=useState(),[result,setResult]=useState(),[history,setHistory]=useState(),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{old?getTestAttempt(old).then(setHistory).catch(e=>setError(e.message)):Promise.all([getTest(id),getTestReviews(id).catch(()=>[])]).then(([t,r])=>{setTest(t);setReviews(r)}).catch(e=>setError(e.message))},[id,old]);async function start(){setBusy(true);try{const value=await startTestAttempt(id);setTest(current=>({...current,questions:value.questions||[]}));setAttempt(value)}catch(e){setError(e.message)}finally{setBusy(false)}}const body=history?<History value={history}/>:result?<div className="chat-shell"><div className="chat-messages"><Result value={result}/></div></div>:attempt?<Chat test={test} attempt={attempt} done={setResult}/>:test?<Start test={test} reviews={reviews} start={start} busy={busy} error={error}/>:<div className="panel error">{error||'Загрузка теста…'}</div>;return <UserLayout active="tests"><main className="dashboard-main chat-profile-main" style={{maxWidth:'none',margin:0,padding:0}}>{body}</main></UserLayout>}
