import { useEffect, useState } from 'react'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import PublicLayout from '../../layouts/PublicLayout'

const blockTypes = [['paragraph','Абзац'],['h2','H2'],['h3','H3'],['bullets','Список'],['numbered','Нумерация'],['quote','Цитата'],['avoid','Как избежать'],['note','Обратите внимание'],['example','Пример'],['conclusion','Вывод'],['checklist','Чек-лист'],['code','Код'],['table','Таблица'],['image','Изображение'],['video','Видео'],['divider','Разделитель']]
function loadEditor() { return new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = '/static/publication-editor.js?v=1'; script.dataset.reactPublicationEditor = 'true'; script.onload = () => resolve(script); script.onerror = () => reject(new Error('Не удалось загрузить редактор публикации')); document.body.append(script) }) }

export default function PublicationEditorPage() {
  useDocumentPage({ title: 'Редактор публикации — FinTalent' })
  usePageStyles(['/static/publication-editor.css?v=1'])
  const [error, setError] = useState('')
  useEffect(() => { let cancelled = false, script; loadEditor().then((value) => { script = value }).catch((loadError) => { if (!cancelled) setError(loadError.message) }); return () => { cancelled = true; script?.remove(); document.querySelectorAll('script[src*="publication-editor"],link[href*="publication-editor-readable"],link[href*="publication-editor-enhancements"]').forEach((element) => element.remove()) } }, [])
  return <PublicLayout><main className="editor-page"><div className="editor-top"><a href="/publications">← Публикации</a><div className="editor-status"><i /><span id="save-status">Новый черновик</span></div><div className="view-switch"><button data-view="editor" className="active">Редактор</button><button data-view="preview">Предпросмотр</button><button data-view="mobile">Мобильный вид</button></div><button id="publish-button" className="publish-button">Опубликовать</button></div>
    <div className="editor-layout"><section className="editor-canvas"><div id="editor-mode"><label className="cover-upload" id="cover-drop"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" /><span>▧</span><b>Добавить обложку</b><small>JPG, PNG или WebP · до 5 МБ</small></label><input id="publication-title" className="title-input" maxLength="240" placeholder="Заголовок публикации" /><input id="publication-subtitle" className="subtitle-input" maxLength="300" placeholder="Подзаголовок" /><textarea id="publication-excerpt" maxLength="800" placeholder="Краткое описание — оно появится в ленте и поиске" /><div className="summary-editor"><header><div><b>За 30 секунд</b><small>Добавьте от 3 до 7 ключевых тезисов</small></div><button id="ai-summary" type="button">✦ Создать автоматически</button></header><div id="summary-items" /><button id="add-summary" type="button">＋ Добавить тезис</button></div><div className="block-toolbar"><span>Добавить блок:</span>{blockTypes.map(([type,label]) => <button data-type={type} key={type}>{label}</button>)}</div><div id="content-blocks" className="content-blocks" /></div><div id="preview-mode" className="preview-mode hidden"><div id="preview-device"><article id="publication-preview" /></div></div></section>
      <aside className="editor-settings"><h2>Настройки публикации</h2><label>Категория<select id="category" defaultValue="0"><option value="0">Выберите категорию</option></select></label><label>Темы<select id="topics" multiple /></label><label>Теги<input id="tags" placeholder="УСН, налоги, отчётность" /></label><label>Профессиональные навыки<select id="skills" multiple /></label><label>Уровень<select id="difficulty" defaultValue="medium"><option value="beginner">Начальный</option><option value="medium">Средний</option><option value="advanced">Продвинутый</option><option value="expert">Экспертный</option></select></label><label>Время чтения<input id="reading-time" type="number" min="1" max="300" defaultValue="5" /></label><label>Серия<select id="series" defaultValue="0"><option value="0">Без серии</option></select></label><label>Номер в серии<input id="series-order" type="number" min="1" defaultValue="1" /></label><label>Связанный тест<select id="test" defaultValue="0"><option value="0">Без теста</option></select></label><label>Язык<select id="language" defaultValue="ru"><option value="ru">Русский</option><option value="en">English</option></select></label><label>Видимость<select id="visibility" defaultValue="draft"><option value="draft">Черновик</option><option value="public">Публичная</option><option value="unlisted">Только по ссылке</option></select></label><label className="check"><input id="allow-comments" type="checkbox" defaultChecked /><span>Разрешить обсуждения</span></label><hr /><label>URL slug<div className="slug-field"><input id="slug" placeholder="adres-publikacii" /><i id="slug-state" /></div></label><label>SEO-заголовок<input id="seo-title" maxLength="240" /></label><label>SEO-описание<textarea id="seo-description" maxLength="320" /></label><label>Что изменилось<input id="change-summary" maxLength="300" placeholder="Для новой версии" /></label><div className="settings-actions"><button id="save-draft" className="secondary">Сохранить</button><button id="delete-publication" className="danger hidden">Удалить</button></div></aside></div>{error && <div id="editor-notice" className="show">{error}</div>}<div id={error ? undefined : 'editor-notice'} /></main></PublicLayout>
}
