import { useEffect, useState } from 'react'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'

const scripts = ['/static/admin.js?v=6','/static/admin-survey.js?v=8','/static/admin-users.js?v=1','/static/admin-publications.js?v=1','/static/admin-client-exchange.js?v=1','/static/admin-accounting-company.js?v=1','/static/admin-help.js?v=1']
function loadScript(src) { return new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = src; script.dataset.reactAdmin = 'true'; script.onload = () => resolve(script); script.onerror = () => reject(new Error('Не удалось загрузить административный модуль')); document.body.append(script) }) }

export default function AdminPage() {
  useDocumentPage({ title: 'Админ-панель — FinTalent' }); usePageStyles(['/static/admin.css','/static/admin-survey.css?v=3'])
  const [error, setError] = useState('')
  useEffect(() => { let cancelled = false; const loaded = []; (async () => { try { for (const src of scripts) { if (cancelled) return; loaded.push(await loadScript(src)) } } catch (loadError) { if (!cancelled) setError(loadError.message) } })(); return () => { cancelled = true; loaded.forEach((script) => script.remove()); document.querySelectorAll('script[src*="/static/admin-"],.ce-admin-modal').forEach((element) => element.remove()) } }, [])
  return <><section id="login-screen" className="login-screen"><form id="admin-login" className="admin-login"><div className="admin-logo">F</div><h1>Админ-панель</h1><p>Управление платформой FinTalent</p><label>Логин<input name="login" autoComplete="username" required placeholder="Введите логин" /></label><label>Пароль<input type="password" name="password" autoComplete="current-password" required placeholder="Введите пароль" /></label><div id="login-error" className="error">{error}</div><button type="submit">Войти в панель <span>→</span></button><a href="/">← Вернуться на сайт</a></form></section>
    <div id="admin-app" className="admin-app hidden"><aside className="sidebar"><a className="sidebar-brand" href="/"><span>F</span><div><b>Fin Talent</b><small>админ-панель</small></div></a><nav><small>УПРАВЛЕНИЕ</small><button id="dictionary-nav" className="active">▤ <span>Справочники</span></button><button id="users-nav">♙ <span>Пользователи</span></button><button id="publications-nav">▥ <span>Публикации</span></button><button id="survey-nav">☷ <span>Опрос соискателя</span></button><button id="vacancy-survey-nav">▷ <span>Создание вакансии</span></button></nav><div className="admin-account"><i>A</i><div><b>Администратор</b><small>admin</small></div><button id="logout" title="Выйти">↪</button></div></aside>
      <main className="workspace"><header><button className="mobile-menu">☰</button><div><h1>Справочники</h1><p>Управление системными вариантами ответов</p></div><button id="new-dictionary" className="primary">＋ Новый справочник</button><button id="new-survey-block" className="primary hidden">＋ Создать блок опроса</button></header><div id="notice" className="notice" /><section id="dictionary-list" className="dictionary-list" /><section id="dictionary-editor" className="dictionary-editor hidden"><button id="back" className="back">← Все справочники</button><div className="editor-head"><div className="dictionary-meta"><label><small>НАЗВАНИЕ СПРАВОЧНИКА</small><input id="dictionary-name" aria-label="Название справочника" /></label><label><small>ALIAS НА АНГЛИЙСКОМ</small><input id="dictionary-alias" aria-label="Alias справочника" placeholder="example_alias" /></label><label className="vacancy-importance-option"><input id="dictionary-use-importance" type="checkbox" defaultChecked /><span><b>Использовать важность в вакансии</b><small>Показывать выбор важности требования</small></span></label></div><button id="delete-dictionary" className="danger">Удалить справочник</button></div><div className="items-head"><div><h2>Варианты ответов</h2><p>Меняйте значения, комментарии и иконки</p></div><button id="add-item" className="secondary">＋ Добавить вариант</button></div><div className="item-columns"><span>№</span><span>Вариант ответа</span><span>Комментарий</span><span>Иконка</span><span /></div><div id="items" className="items" /><footer><span id="item-count" /><button id="cancel" className="secondary">Отменить</button><button id="save" className="primary">Сохранить справочник</button></footer></section>
        <section id="survey-section" className="survey-section hidden"><div id="survey-blocks" className="survey-blocks" /><div id="survey-empty" className="survey-empty hidden"><b>Блоков пока нет</b><p>Создайте первый блок и добавьте справочники.</p></div></section><section id="users-section" className="users-section hidden"><div className="users-table-wrap"><table className="users-table"><thead><tr><th>Почта</th><th>ФИО</th><th>Блокировка</th><th>Пароль</th></tr></thead><tbody id="users-list" /></table></div><div id="users-empty" className="users-empty hidden">Пользователей пока нет</div></section><section id="admin-publications" className="admin-publications hidden"><div className="admin-publication-filters"><input id="admin-publication-search" placeholder="Поиск по названию или автору" /><select id="admin-publication-status" defaultValue=""><option value="">Все статусы</option><option value="draft">Черновики</option><option value="published">Опубликовано</option><option value="hidden">Скрыто</option><option value="blocked">Заблокировано</option><option value="archived">Архив</option></select></div><div id="admin-publication-list" /></section></main></div>
    <div id="new-modal" className="modal hidden"><form id="new-form"><h2>Новый справочник</h2><p>Укажите понятное название и технический alias.</p><label>Название<input name="name" required maxLength="200" /></label><label>Alias<input name="alias" required maxLength="100" pattern="[a-z][a-z0-9_]*" /></label><div><button type="button" id="close-modal" className="secondary">Отмена</button><button className="primary">Создать</button></div></form></div>
    <div id="survey-modal" className="modal hidden"><form id="survey-form"><h2 id="survey-modal-title">Создать блок опроса</h2><p>Один блок — один шаг мастера.</p><label>Название блока<input name="name" required maxLength="200" /></label><fieldset><legend>Справочники в этом блоке</legend><div id="survey-dictionaries" className="survey-dictionary-choices" /></fieldset><div><button type="button" id="close-survey-modal" className="secondary">Отмена</button><button className="primary">Сохранить</button></div></form></div>
    <div id="password-modal" className="modal hidden"><form id="password-form"><h2>Изменить пароль</h2><p id="password-user" /><input type="hidden" name="user_id" /><label>Новый пароль<input type="password" name="password" minLength="8" maxLength="72" autoComplete="new-password" required /></label><div><button type="button" id="close-password-modal" className="secondary">Отмена</button><button className="primary">Сохранить пароль</button></div></form></div></>
}
