import { useEffect, useMemo, useRef, useState } from 'react'
import { createAccountingCompany, getAccountingCompaniesMeta, getMyAccountingCompany, publishAccountingCompany, updateAccountingCompany, uploadAccountingCompanyImage } from '../../api/companies'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import PublicLayout from '../../layouts/PublicLayout'
import WizardStepProgress from '../../components/WizardStepProgress'

const steps=['Основная информация','Направления работы','Услуги и цены','Тарифы','Оформление и проверка']
const blank={name:'Новая бухгалтерская компания',short_description:'',full_description:'',logo:'',city:'',address:'',remote_all_russia:false,founded_year:null,employee_count:null,inn:'',phone:'',email:'',website:'',telegram:'',whatsapp:'',vk:'',work_hours:'',manager_name:'',manager_position:'',manager_photo:'',manager_description:'',manager_user_id:null,accent_style_id:null,header_image_type:'template',header_template_id:null,custom_header_image:'',advantages:[],direction_ids:[],key_direction_ids:[],tax_system_ids:[],services:[],tariffs:[],current_step:1}
const payload=c=>Object.fromEntries(Object.keys(blank).map(key=>[key,c[key]??blank[key]]))
const numberValue=value=>value===''?null:Number(value)

function Input({label,name,company,setCompany,type='text',wide=false}){return <label className={`ac-field ${wide?'wide':''}`}><span>{label}</span><input name={name} type={type} value={company[name]??''} onChange={e=>setCompany(c=>({...c,[name]:type==='number'?numberValue(e.target.value):e.target.value}))}/></label>}
function Text({label,name,company,setCompany,placeholder=''}){return <label className="ac-field wide"><span>{label}</span><textarea name={name} value={company[name]||''} onChange={e=>setCompany(c=>({...c,[name]:e.target.value}))} placeholder={placeholder}/></label>}
function Upload({kind,title,url,round,company,setCompany,setState}){const input=useRef(null);async function upload(e){const file=e.target.files?.[0];if(!file)return;setState('Сохраняем…');try{const result=await uploadAccountingCompanyImage(company.id,kind,file);setCompany(c=>({...c,[kind==='manager'?'manager_photo':kind==='header'?'custom_header_image':'logo']:result.url,...(kind==='header'?{header_image_type:'custom'}:{})}));setState('Все изменения сохранены')}catch(error){setState(error.message)}}return <div className="ac-field"><span>{title}</span><div className="ac-upload"><div className={`ac-upload-preview ${round||''}`}>{url?<img src={url} alt=""/>:'＋'}</div><label>Загрузить<input ref={input} type="file" accept="image/jpeg,image/png" onChange={upload}/></label></div></div>}

const directionIconPaths={
  laptop:['M4 5h16v11H4z','M2 19h20','M9 19h6'],briefcase:['M4 8h16v11H4z','M9 8V5h6v3','M4 12h16','M10 12v2h4v-2'],globe:['M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z','M3 12h18','M12 3c2.5 2.5 3.7 5.5 3.7 9S14.5 18.5 12 21c-2.5-2.5-3.7-5.5-3.7-9S9.5 5.5 12 3Z'],store:['M4 10v10h16V10','M3 10l2-6h14l2 6','M8 20v-6h8v6','M3 10c1.2 2 3.8 2 5 0 1.2 2 3.8 2 5 0 1.2 2 3.8 2 5 0 1.2 2 3.8 2 5 0'],factory:['M3 21V9l6 4V9l6 4V5h6v16Z','M7 17h2','M12 17h2','M17 17h2'],video:['M4 5h16v14H4z','m10 12-5 3v-6l5 3Z'],basket:['M5 9h14l-1.5 10h-11z','m8 9 2-5','m16 9-2-5','M9 13v3','M12 13v3','M15 13v3'],package:['m4 8 8-4 8 4-8 4Z','M4 8v9l8 4 8-4V8','M12 12v9','m8 6 8 4'],building:['M5 21V4h10v17','M15 9h4v12','M8 8h2','M8 12h2','M8 16h2'],heart:['M12 20S4 15.4 4 9.5A4.5 4.5 0 0 1 12 6a4.5 4.5 0 0 1 8 3.5C20 15.4 12 20 12 20Z','M8 12h2l1-2 2 4 1-2h2'],coffee:['M5 8h12v7a5 5 0 0 1-5 5H10a5 5 0 0 1-5-5Z','M17 10h2a2 2 0 0 1 0 4h-2','M8 4v2','M12 3v3'],truck:['M3 6h11v11H3z','M14 10h4l3 3v4h-7Z','M6 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z','M18 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z'],car:['M4 11 6 6h12l2 5','M3 11h18v6H3z','M7 19a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z','M17 19a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z'],book:['M4 5c3-1 5-.5 8 1.5V20c-3-2-5-2.5-8-1.5Z','M20 5c-3-1-5-.5-8 1.5V20c3-2 5-2.5 8-1.5Z'],dialog:['M4 5h13v10H9l-4 4v-4H4Z','M9 9h4','M9 12h6','M18 8h2v9h-5'],users:['M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z','M15.5 10a2.5 2.5 0 1 0 0-5','M3 20v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3','M15 13h1a4 4 0 0 1 4 4v3'],home:['m3 11 9-8 9 8','M5 10v11h14V10','M9 21v-7h6v7'],sparkles:['m12 3 1.3 4.2L17 9l-3.7 1.8L12 15l-1.3-4.2L7 9l3.7-1.8Z','m19 14 .7 2.3L22 17l-2.3.7L19 20l-.7-2.3L16 17l2.3-.7Z','M5 14v5','M2.5 16.5h5'],wrench:['M14 6a5 5 0 0 0-6.5 6.5L3 17l4 4 4.5-4.5A5 5 0 0 0 18 10l-3 2-3-3 2-3Z'],cart:['M3 5h2l2 10h10l3-7H6','M9 20a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z','M17 20a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z'],boxes:['m4 7 5-3 5 3-5 3Z','M4 7v6l5 3 5-3V7','m10 12 5-3 5 3-5 3Z','M14 12v6l5 3 5-3v-6'],person:['M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z','M5 21a7 7 0 0 1 14 0'],hands:['M7 13 4 10a2 2 0 0 0-2 2v3l5 5h4','m17 13 3-3a2 2 0 0 1 2 2v3l-5 5h-4','M12 15S7 12.5 7 8.5A2.5 2.5 0 0 1 12 7a2.5 2.5 0 0 1 5 1.5c0 4-5 6.5-5 6.5Z'],market:['M4 10v10h16V10','M3 10l2-6h14l2 6','M8 14h3v6','M15 14h2','M15 17h2'],monitor:['M3 4h18v13H3z','M8 21h8','M12 17v4','M7 8h5','M7 11h9'],gears:['M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z','M12 3v2','M12 19v2','M3 12h2','M19 12h2','m5.6 5.6 1.4 1.4','m17 17 1.4 1.4','m18.4 5.6-1.4 1.4','M7 17l-1.4 1.4'],
  'arrow-in':['M4 6h10v12H4z','m20 12-5-4v3H9v2h6v3Z'],'arrow-out':['M4 6h10v12H4z','m9 12 5-4v3h4v2h-4v3Z']
}
const directionPalette=[['#eaf2ff','#2864dc'],['#f1edff','#7650d6'],['#e8fbf5','#0b956b'],['#fff3e6','#d87512'],['#e8f8ff','#1682b5'],['#fff0f4','#d34e76']]
function DirectionIcon({type,index}){const colors=directionPalette[index%directionPalette.length],paths=directionIconPaths[type]||directionIconPaths.briefcase;return <span className="ac-direction-icon" style={{'--icon-bg':colors[0],'--icon-color':colors[1]}}><svg viewBox="0 0 24 24" aria-hidden="true">{paths.map((d,i)=><path d={d} key={i}/>)}</svg></span>}

function Basic({company,setCompany,setState}){return <><h2>Основная информация</h2><p className="ac-form-intro">Всё, что поможет клиенту быстро понять, кто вы и как с вами связаться.</p><div className="ac-fields"><Input label="Название компании *" name="name" company={company} setCompany={setCompany}/><Input label="Короткий слоган" name="short_description" company={company} setCompany={setCompany}/><Text label="О компании" name="full_description" company={company} setCompany={setCompany}/><Upload kind="logo" title="Логотип компании" url={company.logo} company={company} setCompany={setCompany} setState={setState}/><Upload kind="manager" title="Фото руководителя" url={company.manager_photo} round company={company} setCompany={setCompany} setState={setState}/><Input label="Город" name="city" company={company} setCompany={setCompany}/><Input label="Адрес" name="address" company={company} setCompany={setCompany}/><label className="ac-inline-check wide"><input type="checkbox" checked={company.remote_all_russia} onChange={e=>setCompany(c=>({...c,remote_all_russia:e.target.checked}))}/> Работаем по всей России</label><Input label="Год начала работы" name="founded_year" type="number" company={company} setCompany={setCompany}/><Input label="Количество сотрудников (необязательно)" name="employee_count" type="number" company={company} setCompany={setCompany}/><Input label="ИНН (необязательно)" name="inn" company={company} setCompany={setCompany}/><Input label="Часы работы" name="work_hours" company={company} setCompany={setCompany}/>{['phone','email','website','telegram','whatsapp','vk'].map(name=><Input key={name} label={({phone:'Телефон',email:'Email',website:'Сайт',telegram:'Telegram',whatsapp:'WhatsApp',vk:'VK'})[name]} name={name} company={company} setCompany={setCompany}/>) }<div className="wide"><h2 style={{marginTop:12}}>Руководитель</h2></div><Input label="ФИО руководителя / основателя" name="manager_name" company={company} setCompany={setCompany}/><Input label="Должность" name="manager_position" company={company} setCompany={setCompany}/><Text label="Коротко о руководителе" name="manager_description" company={company} setCompany={setCompany}/></div></>}
function Directions({company,setCompany,meta,notify}){const cycle=id=>setCompany(c=>{const selected=c.direction_ids.includes(id),key=c.key_direction_ids.includes(id);if(!selected){if(c.direction_ids.length>=10){notify('Можно выбрать до 10 направлений');return c}return {...c,direction_ids:[...c.direction_ids,id]}}if(!key){if(c.key_direction_ids.length>=3){notify('Ключевых направлений может быть не больше 3');return c}return {...c,key_direction_ids:[...c.key_direction_ids,id]}}return {...c,direction_ids:c.direction_ids.filter(x=>x!==id),key_direction_ids:c.key_direction_ids.filter(x=>x!==id)}});const tax=id=>setCompany(c=>({...c,tax_system_ids:c.tax_system_ids.includes(id)?c.tax_system_ids.filter(x=>x!==id):[...c.tax_system_ids,id]}));return <><h2>Направления работы</h2><p className="ac-form-intro">Выберите до 10 направлений. Повторный клик отмечает ключевое — максимум 3.</p><div className="ac-choice-grid ac-direction-choice-grid">{meta.directions.map((d,index)=><button type="button" key={d.id} className={`ac-choice ac-direction-choice ${company.direction_ids.includes(d.id)?'selected':''} ${company.key_direction_ids.includes(d.id)?'key':''}`} onClick={()=>cycle(d.id)}><DirectionIcon type={d.icon} index={index}/><b>{d.name}</b><small>Ключевое</small></button>)}</div><p className="ac-step-help">Системы налогообложения, с которыми вы работаете</p><div className="ac-choice-grid">{meta.tax_systems.map(t=><button type="button" key={t.id} className={`ac-choice ${company.tax_system_ids.includes(t.id)?'selected':''}`} onClick={()=>tax(t.id)}><b>{t.name}</b></button>)}</div></>}
function Services({company,setCompany,meta}){const update=(index,key,value)=>setCompany(c=>({...c,services:c.services.map((row,i)=>i===index?{...row,[key]:value}:row)}));return <><h2>Услуги и цены</h2><p className="ac-form-intro">Покажем на странице компактно: название — цена.</p><div>{company.services.map((row,index)=><div className="ac-service-row" key={index}><select value={row.service_id||''} onChange={e=>update(index,'service_id',numberValue(e.target.value))}><option value="">Выберите услугу</option>{meta.services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min="0" value={row.price_from??''} onChange={e=>update(index,'price_from',numberValue(e.target.value))} placeholder="Цена"/><select value={row.price_type||'from_month'} onChange={e=>update(index,'price_type',e.target.value)}><option value="from_month">от ₽ / мес.</option><option value="month">₽ / мес.</option><option value="from_hour">от ₽ / час</option><option value="hour">₽ / час</option><option value="from_once">от ₽</option><option value="request">по запросу</option></select><button type="button" className="ac-remove" onClick={()=>setCompany(c=>({...c,services:c.services.filter((_,i)=>i!==index)}))}>×</button></div>)}</div><button className="ac-add" type="button" onClick={()=>setCompany(c=>({...c,services:[...c.services,{service_id:null,price_from:null,price_type:'from_month',custom_name:''}]}))}>＋ Добавить услугу</button></>}
function Tariffs({company,setCompany,notify}){const update=(index,key,value)=>setCompany(c=>({...c,tariffs:c.tariffs.map((row,i)=>i===index?{...row,[key]:value}:row)}));return <><h2>Тарифы</h2><p className="ac-form-intro">Добавьте от 1 до 5 понятных тарифов. Каждое преимущество укажите с новой строки.</p>{company.tariffs.map((row,index)=><div className="ac-tariff-edit" key={index}><div className="ac-tariff-edit-head"><input value={row.name||''} onChange={e=>update(index,'name',e.target.value)} placeholder="Название"/><input value={row.subtitle||''} onChange={e=>update(index,'subtitle',e.target.value)} placeholder="Для кого тариф"/><input type="number" min="0" value={row.price??''} onChange={e=>update(index,'price',numberValue(e.target.value))} placeholder="Цена"/><input value={row.period||'в месяц'} onChange={e=>update(index,'period',e.target.value)} placeholder="Период"/></div><textarea value={(row.benefits||[]).join('\n')} onChange={e=>update(index,'benefits',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} placeholder="УСН и ОСНО&#10;до 30 операций"/><div className="ac-tariff-options"><label><input type="checkbox" checked={!!row.popular} onChange={e=>update(index,'popular',e.target.checked)}/> Популярный</label><label><input type="checkbox" checked={row.active!==false} onChange={e=>update(index,'active',e.target.checked)}/> Показывать</label><button type="button" className="ac-remove" onClick={()=>setCompany(c=>({...c,tariffs:c.tariffs.filter((_,i)=>i!==index)}))}>×</button></div></div>)}<button className="ac-add" type="button" onClick={()=>{if(company.tariffs.length>=5)return notify('Можно добавить до 5 тарифов');setCompany(c=>({...c,tariffs:[...c.tariffs,{name:'',subtitle:'',price:null,period:'в месяц',benefits:[],popular:false,active:true}]}))}}>＋ Добавить тариф</button></>}
function Appearance({company,setCompany,meta,setState}){return <><h2>Оформление и проверка</h2><p className="ac-form-intro">Выберите спокойный акцентный цвет и одну из готовых обложек.</p><b>Акцентный цвет</b><div className="ac-accent-grid">{meta.accents.map(a=><button type="button" title={a.name} key={a.id} className={`ac-accent ${company.accent_style_id===a.id?'selected':''}`} style={{background:a.color_value}} onClick={()=>setCompany(c=>({...c,accent_style_id:a.id}))}/>)}</div><b>Изображение шапки</b><div className="ac-header-grid">{meta.headers.map(h=><button type="button" title={h.name} key={h.id} className={`ac-header-option ${company.header_template_id===h.id&&company.header_image_type!=='custom'?'selected':''}`} style={{backgroundImage:`url('${h.image_url}')`}} onClick={()=>setCompany(c=>({...c,header_template_id:h.id,header_image_type:'template'}))}/>)}</div><div style={{marginTop:16}}><Upload kind="header" title="Или загрузите свою обложку" url={company.custom_header_image} company={company} setCompany={setCompany} setState={setState}/></div><div className="ac-review-step"><h2>Готово к публикации</h2><p className="ac-form-intro">Проверим обязательный минимум: название, направление, услуга и тариф.</p></div></>}

export default function AccountingCompanyCreatePage(){useDocumentPage({title:'Моя бухгалтерская компания — FinTalent'});usePageStyles(['/static/accounting-company.css?v=4','/static/accounting-company-direction-icons.css?v=1','/static/wizard-step-progress.css?v=4']);const [meta,setMeta]=useState(null),[company,setCompany]=useState(null),[step,setStep]=useState(1),[state,setState]=useState('Все изменения сохранены'),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),initialized=useRef(false)
  const notify=text=>{setToast(text);setTimeout(()=>setToast(''),2600)}
  useEffect(()=>{const controller=new AbortController();(async()=>{try{const [m,mine]=await Promise.all([getAccountingCompaniesMeta({signal:controller.signal}),getMyAccountingCompany({signal:controller.signal})]);setMeta(m);let value=mine.company;if(!value)value=(await createAccountingCompany({...blank,header_template_id:m.headers[0]?.id||null,accent_style_id:m.accents[0]?.id||null},{signal:controller.signal})).company;value={...blank,...value,direction_ids:(value.direction_ids||[]).map(Number),key_direction_ids:(value.key_direction_ids||[]).map(Number),tax_system_ids:(value.tax_system_ids||[]).map(Number),services:value.services||[],tariffs:value.tariffs||[]};setCompany(value);setStep(Math.max(1,Math.min(5,Number(value.current_step)||1)));initialized.current=true}catch(e){if(e.name!=='AbortError'){setState('Не удалось открыть редактор');notify(e.message)}}})();return()=>controller.abort()},[])
  async function save(value=company,quiet=true){if(!value||saving)return null;setSaving(true);setState('Сохраняем…');try{const result=await updateAccountingCompany(value.id,payload({...value,current_step:step}));setCompany(c=>({...c,...result.company}));setState('Все изменения сохранены');if(!quiet)notify('Черновик сохранён');return result.company}catch(e){setState('Не удалось сохранить');notify(e.message);throw e}finally{setSaving(false)}}
  useEffect(()=>{if(!initialized.current||!company)return;const timer=setTimeout(()=>save(company).catch(()=>{}),700);return()=>clearTimeout(timer)},[company?.name,company?.short_description,company?.full_description,company?.city,company?.address,company?.remote_all_russia,company?.founded_year,company?.employee_count,company?.inn,company?.phone,company?.email,company?.website,company?.telegram,company?.whatsapp,company?.vk,company?.work_hours,company?.manager_name,company?.manager_position,company?.manager_description])
  const cover=useMemo(()=>company?.header_image_type==='custom'?company.custom_header_image:meta?.headers.find(x=>x.id===company?.header_template_id)?.image_url,[company,meta]),directions=company?.direction_ids?.slice(0,4).map(id=>meta?.directions.find(x=>x.id===id)?.name).filter(Boolean)||[]
  if(!meta||!company)return <PublicLayout><main className="ac-wizard-page"><div className="ac-loading-page"><div className="ac-skeleton"/></div></main></PublicLayout>
  const props={company,setCompany,meta,notify,setState};const content=step===1?<Basic {...props}/>:step===2?<Directions {...props}/>:step===3?<Services {...props}/>:step===4?<Tariffs {...props}/>:<Appearance {...props}/>
  async function next(){try{const saved=await save();if(step<5){setStep(step+1);setCompany(c=>({...c,current_step:step+1}));return}const result=await publishAccountingCompany(saved.id);notify('Страница компании опубликована');setTimeout(()=>window.location.assign(`/accounting-companies/view?slug=${encodeURIComponent(result.company.slug)}`),800)}catch{}}
  return <PublicLayout><main className="ac-wizard-page"><div className="ac-wizard-top"><a href="/profile?section=my-company" target="_self">← Моя компания</a><div><span>{state}</span><button className="ac-button ac-button-light" onClick={async()=>{try{await save();window.open(`/accounting-companies/view?id=${company.id}&preview=1`,'_blank')}catch{}}}>Предпросмотр</button></div></div><section className="ac-wizard-title"><span className="ac-kicker">СТРАНИЦА КОМПАНИИ</span><h1>{steps[step-1]}</h1><p>Создайте профессиональную страницу за несколько минут.</p></section><WizardStepProgress steps={steps} current={step-1} onStepChange={index=>setStep(index+1)} ariaLabel="Прогресс создания страницы компании"/><div className="ac-wizard-layout"><section className="ac-form-card"><form onSubmit={e=>e.preventDefault()}>{content}</form><footer><button type="button" className="ac-button ac-button-light" style={{visibility:step===1?'hidden':'visible'}} onClick={async()=>{try{await save();setStep(step-1)}catch{}}}>Назад</button><button type="button" className="ac-button" disabled={saving} onClick={next}>{step===5?(company.status==='published'?'Сохранить':'Опубликовать'):'Продолжить'}</button></footer></section><aside className="ac-live"><span>ПРЕДПРОСМОТР</span><div><div className="ac-live-card"><div className="ac-live-cover" style={cover?{backgroundImage:`url('${cover}')`}:{}}/><div className="ac-live-content"><div className="ac-live-logo">{company.logo?<img src={company.logo} alt=""/>:(company.name||'Б').charAt(0)}</div><h3>{company.name||'Название компании'}</h3><p>{company.short_description||'Коротко расскажите о компании и её сильных сторонах.'}</p><div className="ac-live-tags">{directions.map(x=><span key={x}>{x}</span>)}</div></div></div></div></aside></div></main><div className={`ac-toast ${toast?'show':''}`}>{toast}</div></PublicLayout>}
