import { useEffect, useMemo, useRef, useState } from 'react'
import { createAccountingCompany, getAccountingCompaniesMeta, getMyAccountingCompany, publishAccountingCompany, updateAccountingCompany, uploadAccountingCompanyImage } from '../../api/companies'
import { useDocumentPage } from '../../hooks/useDocumentPage'
import usePageStyles from '../../hooks/usePageStyles'
import PublicLayout from '../../layouts/PublicLayout'
import WizardStepProgress from '../../components/WizardStepProgress'

const steps=['Основная информация','Направления работы','Услуги и цены','Тарифы','Оформление и проверка']
const blank={name:'Новая бухгалтерская компания',short_description:'',full_description:'',logo:'',city:'',address:'',remote_all_russia:false,founded_year:null,employee_count:null,inn:'',phone:'',email:'',website:'',telegram:'',whatsapp:'',vk:'',work_hours:'',manager_name:'',manager_position:'',manager_photo:'',manager_description:'',manager_user_id:null,accent_style_id:null,header_image_type:'template',header_template_id:null,custom_header_image:'',advantages:[],direction_ids:[],key_direction_ids:[],tax_system_ids:[],services:[],tariffs:[],current_step:1}
const payload=c=>Object.fromEntries(Object.keys(blank).map(key=>[key,c[key]??blank[key]]))
const numberValue=value=>value===''?null:Number(value)

function Input({label,name,company,setCompany,type='text',wide=false}){return <label className={`ac-field ${wide?'wide':''}`}><span>{label}</span><input name={name} type={type} value={company[name]??''} onChange={e=>setCompany(c=>({...c,[name]:type==='number'?numberValue(e.target.value):e.target.value}))}/></label>}
function Text({label,name,company,setCompany,placeholder=''}){return <label className="ac-field wide"><span>{label}</span><textarea name={name} value={company[name]||''} onChange={e=>setCompany(c=>({...c,[name]:e.target.value}))} placeholder={placeholder}/></label>}
function Upload({kind,title,url,round,company,setCompany,setState}){const input=useRef(null);async function upload(e){const file=e.target.files?.[0];if(!file)return;setState('Сохраняем…');try{const result=await uploadAccountingCompanyImage(company.id,kind,file);setCompany(c=>({...c,[kind==='manager'?'manager_photo':kind==='header'?'custom_header_image':'logo']:result.url,...(kind==='header'?{header_image_type:'custom'}:{})}));setState('Все изменения сохранены')}catch(error){setState(error.message)}}return <div className="ac-field"><span>{title}</span><div className="ac-upload"><div className={`ac-upload-preview ${round||''}`}>{url?<img src={url} alt=""/>:'＋'}</div><label>Загрузить<input ref={input} type="file" accept="image/jpeg,image/png" onChange={upload}/></label></div></div>}

function Basic({company,setCompany,setState}){return <><h2>Основная информация</h2><p className="ac-form-intro">Всё, что поможет клиенту быстро понять, кто вы и как с вами связаться.</p><div className="ac-fields"><Input label="Название компании *" name="name" company={company} setCompany={setCompany}/><Input label="Короткий слоган" name="short_description" company={company} setCompany={setCompany}/><Text label="О компании" name="full_description" company={company} setCompany={setCompany}/><Upload kind="logo" title="Логотип компании" url={company.logo} company={company} setCompany={setCompany} setState={setState}/><Upload kind="manager" title="Фото руководителя" url={company.manager_photo} round company={company} setCompany={setCompany} setState={setState}/><Input label="Город" name="city" company={company} setCompany={setCompany}/><Input label="Адрес" name="address" company={company} setCompany={setCompany}/><label className="ac-inline-check wide"><input type="checkbox" checked={company.remote_all_russia} onChange={e=>setCompany(c=>({...c,remote_all_russia:e.target.checked}))}/> Работаем по всей России</label><Input label="Год начала работы" name="founded_year" type="number" company={company} setCompany={setCompany}/><Input label="Количество сотрудников (необязательно)" name="employee_count" type="number" company={company} setCompany={setCompany}/><Input label="ИНН (необязательно)" name="inn" company={company} setCompany={setCompany}/><Input label="Часы работы" name="work_hours" company={company} setCompany={setCompany}/>{['phone','email','website','telegram','whatsapp','vk'].map(name=><Input key={name} label={({phone:'Телефон',email:'Email',website:'Сайт',telegram:'Telegram',whatsapp:'WhatsApp',vk:'VK'})[name]} name={name} company={company} setCompany={setCompany}/>) }<div className="wide"><h2 style={{marginTop:12}}>Руководитель</h2></div><Input label="ФИО руководителя / основателя" name="manager_name" company={company} setCompany={setCompany}/><Input label="Должность" name="manager_position" company={company} setCompany={setCompany}/><Text label="Коротко о руководителе" name="manager_description" company={company} setCompany={setCompany}/></div></>}
function Directions({company,setCompany,meta,notify}){const cycle=id=>setCompany(c=>{const selected=c.direction_ids.includes(id),key=c.key_direction_ids.includes(id);if(!selected){if(c.direction_ids.length>=10){notify('Можно выбрать до 10 направлений');return c}return {...c,direction_ids:[...c.direction_ids,id]}}if(!key){if(c.key_direction_ids.length>=3){notify('Ключевых направлений может быть не больше 3');return c}return {...c,key_direction_ids:[...c.key_direction_ids,id]}}return {...c,direction_ids:c.direction_ids.filter(x=>x!==id),key_direction_ids:c.key_direction_ids.filter(x=>x!==id)}});const tax=id=>setCompany(c=>({...c,tax_system_ids:c.tax_system_ids.includes(id)?c.tax_system_ids.filter(x=>x!==id):[...c.tax_system_ids,id]}));return <><h2>Направления работы</h2><p className="ac-form-intro">Выберите до 10 направлений. Повторный клик отмечает ключевое — максимум 3.</p><div className="ac-choice-grid">{meta.directions.map(d=><button type="button" key={d.id} className={`ac-choice ${company.direction_ids.includes(d.id)?'selected':''} ${company.key_direction_ids.includes(d.id)?'key':''}`} onClick={()=>cycle(d.id)}><i>◆</i><b>{d.name}</b><small>Ключевое</small></button>)}</div><p className="ac-step-help">Системы налогообложения, с которыми вы работаете</p><div className="ac-choice-grid">{meta.tax_systems.map(t=><button type="button" key={t.id} className={`ac-choice ${company.tax_system_ids.includes(t.id)?'selected':''}`} onClick={()=>tax(t.id)}><b>{t.name}</b></button>)}</div></>}
function Services({company,setCompany,meta}){const update=(index,key,value)=>setCompany(c=>({...c,services:c.services.map((row,i)=>i===index?{...row,[key]:value}:row)}));return <><h2>Услуги и цены</h2><p className="ac-form-intro">Покажем на странице компактно: название — цена.</p><div>{company.services.map((row,index)=><div className="ac-service-row" key={index}><select value={row.service_id||''} onChange={e=>update(index,'service_id',numberValue(e.target.value))}><option value="">Выберите услугу</option>{meta.services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min="0" value={row.price_from??''} onChange={e=>update(index,'price_from',numberValue(e.target.value))} placeholder="Цена"/><select value={row.price_type||'from_month'} onChange={e=>update(index,'price_type',e.target.value)}><option value="from_month">от ₽ / мес.</option><option value="month">₽ / мес.</option><option value="from_hour">от ₽ / час</option><option value="hour">₽ / час</option><option value="from_once">от ₽</option><option value="request">по запросу</option></select><button type="button" className="ac-remove" onClick={()=>setCompany(c=>({...c,services:c.services.filter((_,i)=>i!==index)}))}>×</button></div>)}</div><button className="ac-add" type="button" onClick={()=>setCompany(c=>({...c,services:[...c.services,{service_id:null,price_from:null,price_type:'from_month',custom_name:''}]}))}>＋ Добавить услугу</button></>}
function Tariffs({company,setCompany,notify}){const update=(index,key,value)=>setCompany(c=>({...c,tariffs:c.tariffs.map((row,i)=>i===index?{...row,[key]:value}:row)}));return <><h2>Тарифы</h2><p className="ac-form-intro">Добавьте от 1 до 5 понятных тарифов. Каждое преимущество укажите с новой строки.</p>{company.tariffs.map((row,index)=><div className="ac-tariff-edit" key={index}><div className="ac-tariff-edit-head"><input value={row.name||''} onChange={e=>update(index,'name',e.target.value)} placeholder="Название"/><input value={row.subtitle||''} onChange={e=>update(index,'subtitle',e.target.value)} placeholder="Для кого тариф"/><input type="number" min="0" value={row.price??''} onChange={e=>update(index,'price',numberValue(e.target.value))} placeholder="Цена"/><input value={row.period||'в месяц'} onChange={e=>update(index,'period',e.target.value)} placeholder="Период"/></div><textarea value={(row.benefits||[]).join('\n')} onChange={e=>update(index,'benefits',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))} placeholder="УСН и ОСНО&#10;до 30 операций"/><div className="ac-tariff-options"><label><input type="checkbox" checked={!!row.popular} onChange={e=>update(index,'popular',e.target.checked)}/> Популярный</label><label><input type="checkbox" checked={row.active!==false} onChange={e=>update(index,'active',e.target.checked)}/> Показывать</label><button type="button" className="ac-remove" onClick={()=>setCompany(c=>({...c,tariffs:c.tariffs.filter((_,i)=>i!==index)}))}>×</button></div></div>)}<button className="ac-add" type="button" onClick={()=>{if(company.tariffs.length>=5)return notify('Можно добавить до 5 тарифов');setCompany(c=>({...c,tariffs:[...c.tariffs,{name:'',subtitle:'',price:null,period:'в месяц',benefits:[],popular:false,active:true}]}))}}>＋ Добавить тариф</button></>}
function Appearance({company,setCompany,meta,setState}){return <><h2>Оформление и проверка</h2><p className="ac-form-intro">Выберите спокойный акцентный цвет и одну из готовых обложек.</p><b>Акцентный цвет</b><div className="ac-accent-grid">{meta.accents.map(a=><button type="button" title={a.name} key={a.id} className={`ac-accent ${company.accent_style_id===a.id?'selected':''}`} style={{background:a.color_value}} onClick={()=>setCompany(c=>({...c,accent_style_id:a.id}))}/>)}</div><b>Изображение шапки</b><div className="ac-header-grid">{meta.headers.map(h=><button type="button" title={h.name} key={h.id} className={`ac-header-option ${company.header_template_id===h.id&&company.header_image_type!=='custom'?'selected':''}`} style={{backgroundImage:`url('${h.image_url}')`}} onClick={()=>setCompany(c=>({...c,header_template_id:h.id,header_image_type:'template'}))}/>)}</div><div style={{marginTop:16}}><Upload kind="header" title="Или загрузите свою обложку" url={company.custom_header_image} company={company} setCompany={setCompany} setState={setState}/></div><div className="ac-review-step"><h2>Готово к публикации</h2><p className="ac-form-intro">Проверим обязательный минимум: название, направление, услуга и тариф.</p></div></>}

export default function AccountingCompanyCreatePage(){useDocumentPage({title:'Моя бухгалтерская компания — FinTalent'});usePageStyles(['/static/accounting-company.css?v=4','/static/wizard-step-progress.css?v=4']);const [meta,setMeta]=useState(null),[company,setCompany]=useState(null),[step,setStep]=useState(1),[state,setState]=useState('Все изменения сохранены'),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),initialized=useRef(false)
  const notify=text=>{setToast(text);setTimeout(()=>setToast(''),2600)}
  useEffect(()=>{const controller=new AbortController();(async()=>{try{const [m,mine]=await Promise.all([getAccountingCompaniesMeta({signal:controller.signal}),getMyAccountingCompany({signal:controller.signal})]);setMeta(m);let value=mine.company;if(!value)value=(await createAccountingCompany({...blank,header_template_id:m.headers[0]?.id||null,accent_style_id:m.accents[0]?.id||null},{signal:controller.signal})).company;value={...blank,...value,direction_ids:(value.direction_ids||[]).map(Number),key_direction_ids:(value.key_direction_ids||[]).map(Number),tax_system_ids:(value.tax_system_ids||[]).map(Number),services:value.services||[],tariffs:value.tariffs||[]};setCompany(value);setStep(Math.max(1,Math.min(5,Number(value.current_step)||1)));initialized.current=true}catch(e){if(e.name!=='AbortError'){setState('Не удалось открыть редактор');notify(e.message)}}})();return()=>controller.abort()},[])
  async function save(value=company,quiet=true){if(!value||saving)return null;setSaving(true);setState('Сохраняем…');try{const result=await updateAccountingCompany(value.id,payload({...value,current_step:step}));setCompany(c=>({...c,...result.company}));setState('Все изменения сохранены');if(!quiet)notify('Черновик сохранён');return result.company}catch(e){setState('Не удалось сохранить');notify(e.message);throw e}finally{setSaving(false)}}
  useEffect(()=>{if(!initialized.current||!company)return;const timer=setTimeout(()=>save(company).catch(()=>{}),700);return()=>clearTimeout(timer)},[company?.name,company?.short_description,company?.full_description,company?.city,company?.address,company?.remote_all_russia,company?.founded_year,company?.employee_count,company?.inn,company?.phone,company?.email,company?.website,company?.telegram,company?.whatsapp,company?.vk,company?.work_hours,company?.manager_name,company?.manager_position,company?.manager_description])
  const cover=useMemo(()=>company?.header_image_type==='custom'?company.custom_header_image:meta?.headers.find(x=>x.id===company?.header_template_id)?.image_url,[company,meta]),directions=company?.direction_ids?.slice(0,4).map(id=>meta?.directions.find(x=>x.id===id)?.name).filter(Boolean)||[]
  if(!meta||!company)return <PublicLayout><main className="ac-wizard-page"><div className="ac-loading-page"><div className="ac-skeleton"/></div></main></PublicLayout>
  const props={company,setCompany,meta,notify,setState};const content=step===1?<Basic {...props}/>:step===2?<Directions {...props}/>:step===3?<Services {...props}/>:step===4?<Tariffs {...props}/>:<Appearance {...props}/>
  async function next(){try{const saved=await save();if(step<5){setStep(step+1);setCompany(c=>({...c,current_step:step+1}));return}const result=await publishAccountingCompany(saved.id);notify('Страница компании опубликована');setTimeout(()=>window.location.assign(`/accounting-companies/view?slug=${encodeURIComponent(result.company.slug)}`),800)}catch{}}
  return <PublicLayout><main className="ac-wizard-page"><div className="ac-wizard-top"><a href="/profile?section=my-company">← Моя компания</a><div><span>{state}</span><button className="ac-button ac-button-light" onClick={async()=>{try{await save();window.open(`/accounting-companies/view?id=${company.id}&preview=1`,'_blank')}catch{}}}>Предпросмотр</button></div></div><section className="ac-wizard-title"><span className="ac-kicker">СТРАНИЦА КОМПАНИИ</span><h1>{steps[step-1]}</h1><p>Создайте профессиональную страницу за несколько минут.</p></section><WizardStepProgress steps={steps} current={step-1} onStepChange={index=>setStep(index+1)} ariaLabel="Прогресс создания страницы компании"/><div className="ac-wizard-layout"><section className="ac-form-card"><form onSubmit={e=>e.preventDefault()}>{content}</form><footer><button type="button" className="ac-button ac-button-light" style={{visibility:step===1?'hidden':'visible'}} onClick={async()=>{try{await save();setStep(step-1)}catch{}}}>Назад</button><button type="button" className="ac-button" disabled={saving} onClick={next}>{step===5?(company.status==='published'?'Сохранить':'Опубликовать'):'Продолжить'}</button></footer></section><aside className="ac-live"><span>ПРЕДПРОСМОТР</span><div><div className="ac-live-card"><div className="ac-live-cover" style={cover?{backgroundImage:`url('${cover}')`}:{}}/><div className="ac-live-content"><div className="ac-live-logo">{company.logo?<img src={company.logo} alt=""/>:(company.name||'Б').charAt(0)}</div><h3>{company.name||'Название компании'}</h3><p>{company.short_description||'Коротко расскажите о компании и её сильных сторонах.'}</p><div className="ac-live-tags">{directions.map(x=><span key={x}>{x}</span>)}</div></div></div></div></aside></div></main><div className={`ac-toast ${toast?'show':''}`}>{toast}</div></PublicLayout>}
